openfaas/faas

README.md
Just a helpful link for people looking to setup Swarm.
=> Added Swarm Setup Tutorial

watchdog/.gitignore, watchdog/config_test.go, watchdog/main.go, watchdog/readconfig.go
* Include unit tests for configuration
* Make timeout configurable
=> Make watchdog configurable

watchdog/main.go
Regarding https://github.com/golang/go/issues/6785#issuecomment-275669472
=> Fix attempt for reported connection buildup

DEV.md, README.md, ROADMAP.md, TestDrive.md, docker-compose.yml, gateway/assets/index.html, gateway/assets/script/bootstrap.js, gateway/handlers/functionshandler.go, sample-functions/NodeInfo/main.js
Adjust documentation for clarity
Allow content-type for UI
Filter non-functions by container label "function"
=> Adjust documentation & allow content-type for UI

debug.md, gateway/assets/script/bootstrap.js, gateway/build.sh, gateway/handlers/functionshandler.go, gateway/handlers/proxy.go, gateway/metrics/metrics.go, gateway/metrics/swarmwatcher.go, gateway/server.go
Simplify amount of metrics recorded and include http service responses.  
Provides richer set of data
Clears up ambiguity with multiple metrics.
Tested on local Docker swarm and with Travis build.
=> Record status codes

community.md
Updated community.md with the 2 events which I will be presenting the faas project.
=> Added Rackspace & ETH Polymesse event demos

.travis.yml, DEV.md, gateway/Dockerfile.build, sample-functions/DockerHubStats/Dockerfile, sample-functions/MarkdownRender/Dockerfile.build, sample-functions/WebhookStash/Dockerfile, watchdog/Dockerfile
Updating Golang version to 1.7.5.
Keeping up to date / consistent across examples.
=> Push Go to 1.7.5

community.md
added TechLancaster event to community.md
=> added TechLancaster event to community.md

gateway/assets/index.html, gateway/handlers/functionshandler.go, gateway/handlers/proxy.go, gateway/tests/integration/README.md, gateway/tests/integration/routes_test.go, sample-functions/ApiKeyProtected/.gitignore, sample-functions/ApiKeyProtected/Dockerfile, sample-functions/ApiKeyProtected/Dockerfile.build, sample-functions/ApiKeyProtected/README.md, sample-functions/ApiKeyProtected/build.sh, sample-functions/ApiKeyProtected/handler.go, watchdog/.gitignore, watchdog/Dockerfile, watchdog/Dockerfile.armhf, watchdog/build.armhf.sh, watchdog/build.sh, watchdog/main.go, watchdog/readconfig.go, watchdog/types/types.go
Forward client headers to functions
For some integrations passing an additional header such as X-Api-Key is needed. 
Relates to: #32 
Tested through adding debug_headers env variable to watchdog component. Integration test added to prove headers are forwarded.
=> Forward client headers to functions

TestDrive.md
Added more details in the `Add new functions to FaaS at runtime` section including a screenshot and explanation of each field when creating a new function with the UI
To help other users with creating UI functions
=> Added more details to the AddFunctions via UI documentation

community.md
Updated community.md to include the GitHub to airtable integration I'll be using for my TechLancaster Talk. This PR includes no code changes
=> updated community.md to include projects/use case section

sample-functions/BaseFunctions/README.md, sample-functions/BaseFunctions/coffee/Dockerfile, sample-functions/BaseFunctions/coffee/build.sh, sample-functions/BaseFunctions/coffee/handler.coffee, sample-functions/BaseFunctions/coffee/package.json
updated Dockerfile and package.json
Adds another language for base function testing
Deployed new base function as a FaaS function and tested functionality through the frontend gateway UI
- [ x] New feature (non-breaking change which adds functionality)
=> added coffeescript example to sample-functions/BaseFunctions

gateway/handlers/alerthandler.go
Enable handling of multiple concurrent alerts
PoC was hard-coded to only read first event, this causes scaling of wrong services.
Replaying json against sample stack
```
{
"receiver": "scale-up",
"status": "firing",
"alerts": [
{
"status": "resolved",
"labels": {
"alertname": "APIHighInvocationRate",
"code": "200",
"function_name": "func_echoit",
"instance": "gateway:8080",
"job": "gateway",
"monitor": "faas-monitor",
"service": "gateway",
"severity": "major",
"value": "5.2"
},
"annotations": {
"description": "High invocation total on gateway:8080",
"summary": "High invocation total on gateway:8080"
},
"startsAt": "2017-04-13T14:56:27.805Z",
"endsAt": "2017-04-13T15:00:52.805Z",
"generatorURL": "http://84e1980973da:9090/graph?g0.expr=rate%28gateway_function_invocation_total%5B10s%5D%29+%3E …
```
=> Enable handling of multiple concurrent alerts

community.md
I created three functions:
- ascii art generator from URL
- first N fib numbers
- URL shortener (relies on external service)
=> Adds some examples to the use cases

appveyor.yml, sample-functions/BaseFunctions/golang/Dockerfile.win, watchdog/Dockerfile.win, watchdog/build.ps1
Build watchdog and sample function for Windows
Provide serverless functions on Windows 10/Server.
Via watchdog on Windows 2016 - not through Docker stack yet.
=> Windows port - spike

LICENSE, gateway/assets/script/bootstrap.js, gateway/handlers/alerthandler.go, gateway/handlers/functionshandler.go, gateway/handlers/proxy.go, gateway/metrics/metrics.go, gateway/metrics/swarmwatcher.go, gateway/requests/requests.go, gateway/tests/alerthandler_test.go, gateway/tests/integration/createfunction_test.go, gateway/tests/integration/deletefunction_test.go, gateway/tests/integration/routes_test.go, gateway/tests/unmarshall_test.go, watchdog/config_test.go, watchdog/main.go, watchdog/requesthandler_test.go, watchdog/types/types.go
Added MIT license line into Golang code files.
Required by license.
=> Add license into code files for MIT

community.md
Added a new speaking event to community.md
=> Added MakerShift to community.md

sample-functions/BaseFunctions/cobol/Dockerfile, sample-functions/BaseFunctions/cobol/build.sh, sample-functions/BaseFunctions/cobol/handler.cob, sample-functions/BaseFunctions/cobol/hello.cob
FaaS is the perfect platform to run Cobol
https://twitter.com/michael_beh/status/860103458308980738
Create a new function and give "./handler" as the fprocess and `functions/base:cobol` as the Docker image.
=> FaaS does Cobol :-)

README.md
=> Add try in pwd button.

sample-functions/Phantomjs/Dockerfile, sample-functions/Phantomjs/README.md, sample-functions/Phantomjs/cnn.js, sample-functions/Phantomjs/feedly_subscribers.js
Example of how to drive Phantomjs via a FaaS function for scraping or automation.
Included in README.md
=> Add sample scraping/automation example via Phantomjs

README.md
Fix url in readme to cli github repo
=> Fix url in readme to cli

community.md
The example documents how to setup an image recognition FaaS based on Tensorflow.
=> Adding faas-tensorflow to community page

docker-compose.yml, gateway/Dockerfile.build, gateway/Dockerfile.build.armhf, gateway/Dockerfile.multistage, gateway/Dockerfile.newbuild, gateway/handlers/alerthandler.go, gateway/handlers/externalprovider.go, gateway/plugin/external.go, gateway/requests/requests.go, gateway/server.go, gateway/tests/config_test.go, gateway/types/http_adapter.go, gateway/types/readconfig.go
Merge Feature - external plugin support (i.e. kubernetes)
Allows an external orchestrator or service to respond to Gateway calls.
Tested with FaaS-netes and FaaS on Swarm.
https://github.com/alexellis/faas-netes
=> Feature - external plugin support (i.e. kubernetes)

community.md
This PR adds the Img2ANSI function to the Community document.
Another Go example, this time using a multi-stage build with dep for the function.
Tested locally using the curl statement in the source repos README.
=> Add Img2ANSI function to community.md

community.md
Let's try this again -- adding in time2Code project on the communities page
=> Time2Code community page addition

docker-compose.yml, gateway/handlers/functionshandler.go, gateway/server.go
Relates to https://github.com/alexellis/faas-cli/issues/33 upstream issue in Docker Swarm.
Allows functions to restart up to 5 times, this means less of the need to "re-deploy" functions.
Locally.
=> Allow restarts of up to 5 times with 5 sec delays

community.md
Adds QR Code function to the community list:
- https://github.com/faas-and-furious/qrcode
=> Add QR Code function to community list

gateway/handlers/externalprovider.go, gateway/handlers/reader.go, gateway/plugin/external.go, gateway/server.go, gateway/types/http_adapter.go, gateway/types/readconfig.go, watchdog/readconfig.go
* Add MIT headers after refactoring into new files
=> Add MIT headers after refactoring into new files

sample-functions/BaseFunctions/R/Dockerfile, sample-functions/BaseFunctions/R/README.Rmd, sample-functions/BaseFunctions/R/README.md, sample-functions/BaseFunctions/R/build.sh, sample-functions/BaseFunctions/R/handler.R
add sample functions for R language with alpine image.
r-base official image repository does not support alpine image but recommend other repository. please see below issue.
<https://github.com/rocker-org/rocker/issues/231>
So i use build that repo dockerfile for R language alpine.
And add r lang sameple functions for faas. 
<https://github.com/alexellis/faas/issues/152>
- [] I have updated the documentation accordingly.
=> Proposal: add sample for R lang

sample-functions/BaseFunctions/R/Dockerfile, sample-functions/BaseFunctions/R/README.Rmd, sample-functions/BaseFunctions/R/README.md, sample-functions/BaseFunctions/R/build.sh, sample-functions/BaseFunctions/R/handler.R, sample-functions/BaseFunctions/README.md
only add readme base functions sample list in R
=> add 	R example on list

CONTRIBUTING.md
For attention @johnmccabe @rgee0 - any additional points we wanted to cover/explain?
=> Update CONTRIBUTING.md guide

gateway/handlers/createhandler.go, gateway/requests/requests.go
Allow constraints such as node.os / node.role to be used in functions
Proposal - #101 
Via CLI with and without "worker" constraint on single host which was a manager.
=> Handle Swarm constraints

gateway/handlers/reader.go, gateway/metrics/add_metrics.go, gateway/metrics/prometheus_query.go, gateway/server.go, gateway/tests/config_test.go, gateway/types/readconfig.go
Fixes #116 - related #166 
Also provides metrics for all external providers.
Via Hyper.sh, Docker Swarm and Kubernetes
=> Query Prometheus API for stats.

gateway/assets/img/icons/ic_delete_black.svg, gateway/assets/index.html, gateway/assets/script/bootstrap.js
Added a delete button to the gateway UI.
The related issue is at #137 
I have tested confirming deletion and canceling deletion via the confirm dialog.
I've added a `delete icon` from [material icons](https://material.io/icons/#ic_delete). The icons are available under the Apache License Version 2.0.
=> Added feature to delete functions from the UI

community.md
Signed-off-by: Luc Juggery <luc.juggery@gmail.com>
Only added entry referencing Reverse Geocoding function in community.md. Function also added to https://github.com/faas-and-furious.
n/a
n/a
n/a
n/a
=> Add Reverse geocoding function in Community

community.md
Added a blog post. @alexellis I also changed the author of my post but was that all right? Thanks!
=> Added 'Integrating OpenFaaS and GraphQL'

community.md
I added two blog posts to the community.md. It help Azure user to use OpenFaaS.
I hope this helps.
=> Adding blogs for Azure

gateway/handlers/update_handler.go, gateway/server.go, gateway/tests/integration/createfunction_test.go
Adds update as a faster deployment option instead of only delete/deploy
=> [WIP] Add update endpoint/route

guide/kong_integration.md
=> Adding Kong guide

community.md
Signed-off-by: Alex Young <alex@heuris.io>
=> Add event to community.md

community.md
Added a GraphQL Blog Post Entry.
=> added graphql blog post

community.md
Signed-off-by: Dinesh Majrekar dinesh.majrekar@serverchoice.com
Added Blog Post
=> Added OpenFaaS on Civo Blog post

community.md
This PR adds the pending OpenFaaS talks to be given in Belfast, Northern Ireland.
Talk names/slide decks to be added in the next week or so.
=> Add Belfast Meetups to events

community.md
This change adds my Telegram Bot Tutorial article to the `community.md` file.
N/A
=> Adding Telegram Bot Tutorial to community.md

community.md
=> Added DCOS provider

docker-compose.yml, gateway/assets/index.html, gateway/assets/newfunction.html, gateway/assets/script/bootstrap.js, gateway/assets/style/bootstrap.css
- If `POST /system/functions` errors then a toast is displayed to the user with the error message and the dialog remains open.
- If `POST /system/functions` succeeds then a toast is displayed to the user with the message "Function created" and the dialog closes.
Related to #195 
Manually testing the UI
=> [WIP] Display function creation error in UI

guide/traefik_integration.md
Added a Traefik setup guide to enable Basic Auth and SSL support
Adds an additional API gateway implemenation. Easy setup for Basic Auth and SSL support
Issue #229 
I went through the guide step by step. 
Ubuntu 17+ w/ Docker 17.06 CE
No code changes necessary
=> [WIP] Traefik integration

guide/README.md
Signed-off-by: austinfrey <aafrey85@gmail.com>
Added a pointer to the initial function debugging discussion #223 
Allows for preliminary remote debugging of node and python functions
#223 
No code changes needed.
=> Added link to initial debugging discussion to guide/README.md

.travis.yml, gateway/Dockerfile, watchdog/Dockerfile
Sync with CLI's Dockerfile for gofmt & go test
Sync with CLI's travis: golang 1.8.3 as build
Do we need an issue?
Travis
=> Update Dockerfile & travis

community.md
Adds todays New Stack piece to the community page.
n/a
n/a
n/a
=> Add New Stack piece on OpenFaaS

community.md
The New Stack have updated the title of yesterdays post, this corrects the title in the industry list and also tidies the url.
n/a
n/a
n/a
=> Update TNS article title and link

README.md, guide/README.md
Signed-off-by: Mark Peek <markpeek@vmware.com>
README changes reflecting the switch from using the twitter username open_faas to openfaas.
=> Update twitter: open_faas => openfaas

sample-functions/samples.yml
Converts the function names in samples.yml to lowercase
Allows sample functions to be deployed on Docker Swarm, k8s.
Fixes https://github.com/openfaas/faas/issues/265
1. `docker swarm init`
2. `./deploy_stack.sh`
3. `cd` into the two functions that require running `./build.sh` first and running it (eg, `docker build` fails due to missing `./app` folder)
4. `faas-cli build -f samples.yml`
5. `faas-cli deploy -f samples.yml`
Works on OSX 10.13
Result of `faas-cli deploy`
```
[@work sample-functions (master ✗)]$ faas-cli deploy -f samples.yml
Deploying: nodeinfo.
No existing service to remove
Deployed.
URL: http://localhost:8080/function/nodeinfo
200 OK
Deploying: webhookstash.
No existing service to remove
Deployed.
URL: http://localhost:8080/function/webhookstash
200 OK
Deploying: …
```
=> Convert function names to lowercase

api-docs/swagger.yml
Signed-off-by: Elliott Beach <elliott2.71828@gmail.com>
Async functions were implemented in #131, swagger doc says WIP
- [x ] My code follows the code style of this project.
=> Update api-doc to say async functions are implemented

community.md
Signed-off-by: Alex Young <alex.young@myunidays.com>
=> Update community.md with slides

gateway/handlers/proxy.go, gateway/tests/proxy_test.go
Fixes #312 content-type pass through
New unit tests, testing via DfM. Fixes for Docker Swarm but need to find out whether this is an issue on K8s.
=> Fixes 312 content-type pass through

community.md
Created a blog post about my experience becoming a contributor to OpenFaaS and the great team here
Added my blog post to the community.md file
Document only change, no testing required
=> Added blog post to community

guide/README.md, guide/deployment_digitalocean.md
This commit adds an initial draft of the DigitalOcean getting started
guide.
Provides a guide to installing OpenFaaS on DigitalOcean. Covers the following cases:
https://github.com/alexellis/faas/issues/172
Deployed/deleted environments on DigitalOcean multiple times.
=> Add Guide to deploying OpenFaaS on DigitalOcean (with Swarm)

gateway/handlers/createhandler.go, gateway/handlers/update_handler.go, gateway/requests/requests.go
Add label support to Swarm
For: #178 and https://github.com/openfaas/faas/issues/175
Tested through faas-CLI - you should see `function: true` by default and any additional labels added.
=> Add label support to Swarm

community.md, guide/README.md
I've provided a CI/CD pipeline using OpenFaaS and added links to the docs.
* Added blog post to community.md
* Added the same link to the `guide/README.md`
#295
=> added a blog post related to CI/CD pipeline

gateway/README.md, gateway/types/readconfig.go
Add docs regarding gateway environment varialbes, and simple README.
Related #298
List out the environment variables that can be used.
Documentation, no tests.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
=> Docs for Gateway environment variables

gateway/assets/index.html
Link the icon in the OpenFaaS portal to www.openfaas.com.
=> Add link to www.openfaas.com on OpenFaaS Icon.

gateway/handlers/asyncreport.go, gateway/handlers/proxy.go
Report async execution duration for work with the asynchronous stack.
Issue raised/reported by @developius
=> Report async execution duration

guide/deployment_swarm_ARM.md
Signed-off-by: rgee0 richard@technologee.co.uk
Adaptation of the swarm deployment and the morning coffee blog with changes made to address the differences required to enable the sample function to build and invoke correctly on an ARM.  Further work required to accommodate ARM64
The current guides focus on x86_64 meaning there is a lack of information about the changes required to enable OpenFaaS on ARM hardware.  Fixes #307.
Followed the guide on armhf.  
Further edits required for arm64 & once changes in #321 are merged.
=> [WIP] Draft Quick guide for ARMHF / ARM64 fixes #307

community.md
Signed-off-by: mlabouardy <mohamed@labouardy.com>
=> serverless memes function post link

watchdog/main.go
Logs the beginning of the fork process execution. Prints duration/total execution-time in logs of function.
=> Log fork/duration

community.md
=> Add Oli's & my talk/blogs to community.md

sample-functions/DockerHubStats/Dockerfile
Signed-off-by: Liz Rice <liz@lizrice.com>
Add healthcheck to DockerHubStats sample function
Adds healthcheck so that it meets liveness checks when running under Kubernetes (otherwise the pod keeps being restarted)
Ran sample function under OpenFaaS on Kubernetes
=> Add healthcheck to DockerHubStats sample function

gateway/Dockerfile, watchdog/Dockerfile
This commit bumps the Go version used in the builder images from `1.8.3` to `1.8.5`.
Skipped raising an issue due to the trivial nature of the change.
Pulls in the following fixes:
- go1.8.4 (released 2017/10/04) includes two security fixes.
- go1.8.5 (released 2017/10/25) includes fixes to the compiler, linker, runtime, documentation, go command, and the crypto/x509 and net/smtp packages. It includes a fix to a bug introduced in Go 1.8.4 that broke go get of non-Git repositories under certain conditions.
Built gateway and watchdog, spun up gateway and a new function built on the watchdog. No issues observed.
=> Bump go version to 1.8.5

api-docs/swagger.yml
=> Add note about when /async-function/{functionName} can be invoked.

gateway/handlers/proxy.go
Don't buffer body / response into memory
#340 
Via shrink-image function and url-ping
=> Don't buffer body / response into memory

community.md
Added in November 20th Docker Cambridge event where Alex is speaking.
=> Add in Docker Cambridge event to community 

community.md
Adds an entry to the Industry awards and mentions section of the community doc.
I have not raised an issue as this is a trivial change.
n/a
n/a
=> Add CNCF Landscape to Industry mentions

guide/asynchronous.md
Trivial update to fix the example route in guide/asynchronous.md
I've **not** raised an issue as the change is trivial.
n/a
=> Fix route in example function call

gateway/assets/index.html, gateway/assets/script/bootstrap.js
Display client-round-trip time in seconds in the UI
Useful for understanding latency / duration for various functions. Note this reflects client trip-time, not function execution time which is recorded in Prometheus
=> Display client-round-trip time in seconds in the UI

community.md
Add OpenFaaS presentation and demo on Kubernetes @ Paris Serverless Meetup
=> Add OpenFaaS presentation and demo on Kubernetes

community.md
Signed-off-by: Robbie Page <rob@rorpage.com>
Add a blog entry per Alex's request
Update to community.md
N/A
N/A
=> add Panos' blog entry to community.md

community.md
Signed-off-by: Johnny Mkhael <johnny.mkhael@gmail.com>
Adding Multi-style Artist/Pastiche Generator Blog post
The  Blog explains how to use Google Brain project Magenta and OpenFaaS to build a Serverless function which will enable us to do multi-style transfer.
=> Adding artist blog

.DEREK.yml
Adds a .DEREK.yml file which is a migration of MAINTAINERS so that the repo can be managed by the latest version of Derek.
Derek is evolving.  This change enables the repo to grow with him.
=> Adding .DEREK.yml to enable more granular permissions fixes #406

gateway/handlers/cors.go, gateway/server.go
Part one of the OpenFaaS Function Store
This change allows CORS requests to GitHub's raw CDN from the Portal / Web UI
This is on the ROADMAP
Along with @kenfdev - allows client UI to reach out to raw JSON files on GitHub's CDN
Documented here - https://github.com/openfaas/store
=> Allow CORS to GitHub for Function Store

guide/asynchronous.md
Updating k8s kubectl create and apply command in the doc
```
kubectl -f apply ./faas.async.yml,nats.yml
Error: unknown command "./faas.async.yml,nats.yml" for "kubectl"
Run 'kubectl --help' for usage.
```
=> Fixing typo in asynchronous.md

README.md
Updated the Grafana dashboard and added it to the [Grafana Dashboards](https://grafana.com/dashboards/3434) directory. 
Created a new charts, logo, filters, and updated the layout of the Dashboard
This update helps add some of the newer functionality available from Grafana to the dashboard
This has been tested with a local instance running on my Mac. I have gone through the different scenarios of scaling, measuring execution times and it appears to be reporting correctly.  Please provide feedback as I will continue updating.
- [X ] New feature (non-breaking change which adds functionality)
=> Updated Grafana Dashboard and screenshot

docker-compose.extended.yml, docker-compose.yml
=> Bump versions for store

community.md
Add "Deploying OpenFaaS on Kubernetes  - AWS" to community.md file
Signed-off-by: Eric Stoekl <ems5311@gmail.com>
Adds my OF+K8s+AWS post to community.md file.
N/A
=> Add blog post from Eric to community.md

.DEREK.yml, MAINTAINERS
I'd like to help maintain the OpenFaaS project by finding help in issues and PRs by utilizing Derek
I didn't raise an issue, but I _did_ speak with Alex IRL :)
=> Adding BurtonR to list of maintainers

community.md
Signed-off-by: Mauricio Farache <mauricio.farache@piksel.com>
Added new entry in the blogs sections with a reference to my recent blog post on my personal blog about openFaas with Kubernetes. I tried to explore as many items as possible. Everything worked like a charm.
Sharing knowledge
No test nor changes to the code
No changes to code
- [ X] I have updated the documentation accordingly.
- [ X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ X] I have signed-off my commits with `git commit -s`
=> Added new entry in community.md - blogs section - for Functions as a Service with openFaas

community.md, guide/README.md
* Added blog post to community
* Added blog post related to CI/CD to the guides
=> Added blog posts

gateway/assets/script/bootstrap.js
Adds env-vars to store
Needed for the inception function so that it doesn't time-out due to the defaults for the function.
=> Adds env-vars to store

gateway/assets/index.html, gateway/assets/script/bootstrap.js
UI: allow binary download
Related #433
Through store and new "download" option-box.
Specify the file-extension via com.openfaas.ui.ext label - i.e. `.mp3`
Docs updated on store for new label property.
=> UI: allow binary download

gateway/README.md, gateway/handlers/callid_middleware.go, gateway/server.go
Adds a call-id as a middleware for all calls passing through gateway
To enable debugging and tracing
Via local build with Swarm
=> Add call-id via middleware

community.md
Signed-off-by: Alberto Quario <realbot@gmail.com>
=> Added DCOS blog post

.gitignore, community.md
GKE articles:
* [Running OpenFaaS on GKE - a step by step guide](https://www.weave.works/blog/openfaas-gke)
* [How to secure OpenFaaS with Let's Encrypt and basic auth on Google Kubernetes Engine](https://stefanprodan.com/2017/openfaas-kubernetes-ingress-ssl-gke/)
=> Added GKE articles

api-docs/swagger.yml, deploy_extended.sh, docker-compose.yml, guide/asynchronous.md, sample-functions/BaseFunctions/R/README.Rmd
Remove non-async option for deployment
#458 
Locally with DfM on my laptop
* Async still works
* Sync still works
=> Remove non-async option for deployment

gateway/metrics/add_metrics.go
Escape PromQL query in code rather than inline.
Easier to read/maintain this way - came up on slack discussion today.
Local OpenFaaS cluster on DfM + Swarm. UI still reports invocation count correctly. 
```
ID                  NAME                 IMAGE                       NODE                    DESIRED STATE       CURRENT STATE           ERROR                       PORTS
tfm8wxbs9v7t        func_gateway.1       functions/gateway:0.6.16a   linuxkit-025000000001   Running             Running 2 minutes ago                               
```
=> Escape PromQL query

community.md
=> Add T3chFest event

guide/backends.md
The existing image in `guides/backends.md` has been cleaned up by @amiryal.  Simple change to replace the image in the .md with the one uploaded in the issue.  Fixes #475 
[Viewed here](https://github.com/rgee0/faas/blob/updateBackendsImage/guide/backends.md)
More enhancement than a bug.
=> Changing backends.md image to clearer version - fixes #475

README.md
Signed-off-by: Umesh Yadav <umesh4257@gmail.com>
Enabled the try-with-pwd button in the readme.
fixes #485 
I works absolutely fine on browser both in normal and incognito mode.
cc / @alexellis
=> Add try with PWD button in the readme.

community.md
Add ColoriseBot: three months on post to community.md
=> Add ColoriseBot post to community.md

community.md
Adds blog post for Deploying OpenFaaS on Azure AKS to the `community.md` file.
=> Add Deploying OpenFaaS On Azure AKS Blog Post

gateway/tests/config_test.go, gateway/types/readconfig.go
=> [Ready to Merge] Support Go durations for timeout values

community.md
Signed-off-by: Laurent Grangeau <laurent.grangeau@gmail.com>
Add conferences around France
I have added 4 conferences around OpenFaaS I did the past 2 months in France, and 2 I'll do in the coming months
=> Add conferences around France

guide/deployment_k8s.md
=> Fix for faas-invoke - flag should be '-g' or '--gateway'

community.md
Added my blog post to the community guides.
=> Scaleway bare-metal blog post

gateway/assets/index.html, gateway/assets/script/bootstrap.js
The recent version of AngularJS is 1.6. It has some bug fixes (of AngularJS itself) and performance, security improvements.
Despite the HTTP Header being `text/plain`. AngularJS tried to parse JSON like texts which leads to an `undefined` response. `1.6.6` and above fixes this problem inside the `$http` service.
I've read the changes from the [AngularJS official docs](https://docs.angularjs.org/guide/migration) and the only breaking change should be the one mentioned above (use `then/catch` rather than `success/error` )
#528
#530 
Browsers I've tested:
* Chrome 63.0.3239.132
* Firefox 57.0.1 
* Safari 11.0.3
Features I've tested:
* Auto refreshing function list
* Deploy a new function from
* store
* manually
* Delete functions
* Invoke …
=> Upgraded AngularJS from 1.5.5 to 1.6.9

docker-compose.yml
=> update read/write timeout config in seconds

docker-compose.yml
Bump tags for Gateway / FaaS-Swarm
GW 0.7.2 (triggered by following build)
FaaS-Swarm (built today for timeouts)
=> Bump tags for Gateway / FaaS-Swarm

community.md
Added my recent blog posts and a github repo to the community file. Also, fixed my username on hackernoon
No open issue, just blogging
Tested the blog content while writing. No reports yet of troubles from anyone reading
Add lines to the community file
=> Added 2 blog posts and 1 repo by burtonr to community.md

gateway/assets/index.html, gateway/assets/script/bootstrap.js
The current gateway UI wasn't working on IE11. (It was completely a blank page for me)
I looked at the error and found some ES6 arrow function syntax in the uuidv4 function.
I fixed it to use normal `function` syntax.
In addition, after being able to see the UI again, I found that the layout wasn't working well with IE11, too. Found that the HTML didn't have a proper closing tag, hence the layout didn't work well.
(probably other browsers auto-fix these problems)
#537 
* IE11
* Chrome 63.0.3239.132
=> Fixed broken IE behavior

README.md
Signed-off-by: Michael Herman <hermanmu@gmail.com>
=> fixed whitespace for the python example

gateway/assets/script/bootstrap.js
Deleted some unnecessary variables and `$scope` variables.
* Chrome
No change in functionality of the original branch. Just linted a little.
=> Edited unnecessary fields and `$scope`s.

gateway/assets/index.html, gateway/assets/script/bootstrap.js
Suppose you had function A and B.
Delete function B and then select function A before B gets deleted from the UI.
When function B disappears from the UI, function A's Status becomes `Not Ready`.
This is because, when the `$scope.functions` updates its property by fetching from `system/functions`, the `$scope.selectedFunction` object changes (even though all the properties are the same, it's a different object.
This means
```
refreshFunction($scope.selectedFunction);
```
isn't updating the newly fetched version of the `selectedFunction`, hence even though it's `Ready`, the UI doesn't get updated.
There may be a better way but for now what I came up of is to update the selected function when the `$scope.functions` length changes.
Plus, I found …
=> fixed unexpected behavior where the selected function properties don't get updated

sample-functions/DockerHubStats/main.go
Resolves #561 
Updated hubstats sample function to accept repository input (`username/repository`) that will return the pull count
Also, separated the call to the docker api and parsing the response to make it easier to add more information to either request/response later on (stars, etc).
Using PWD, deployed function and used `burtonr` and `burtonr/movies` as input. Validated response with the information displayed on Docker Hub
=> updated hubstats to accept repo for pull count

.DEREK.yml
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>
Added myself to the maintainers list
=> Added Stefan to maintainers

guide/self_hosted_registry.md
document for https://github.com/openfaas/faas/issues/242
=> [WIP] Self hosted registry guide

contrib/alertmanager-armhf/0.15.0-rc.0/Dockerfile, docker-compose.armhf.yml
Added a `Dockerfile` for AlertManager under `contrib`.  `Dockerfile` based on https://github.com/alexellis/docker-arm/blob/master/images/armhf/alertmanager/Dockerfile.
Changes to `docker-compose.armhf.yml`:
- added a label to the network
- changed the alertmanager image (This will need changing before merge, once the image is pushed to the project repo).
- edited the `command` section for the alertmanager service
- [ x ] There is an issue to propose this change (fixes #582)
[WIP]
=> [WIP] ARM alertmanager Dockerfile and associated compose changes

gateway/Dockerfile, gateway/handlers/forwarding_proxy.go, gateway/server.go
* Break out logging into separate methods
Simplifies the code used to log requests and metrics
Makes logging one line instead of two for each request.
New style:
```
func_gateway.1.y1ak3m67vx9r@alexx    | 2018/03/14 15:17:05 Forwarded [POST] to /function/nodeinfo - [200] took 0.145605 seconds
```
Tested on Docker Swarm
=> Break out logging / metrics for functions in forwarding_proxy

community.md
After reviewing the community.md file, I found that one of my blog posts had not been added from back in November 2017
No testing, just a blog post entry
=> Community.md missing blog post by BurtonR

community.md
Adding a blog post on securing Kubernetes for OpenFaaS
Signed-off-by: Daniel Shapira <daniel@twistlock.com>
=> Add Twistlock's blog post

gateway/assets/script/bootstrap.js
This fixes Invoke/Download errors on IE11
[#537](https://github.com/openfaas/faas/issues/537)
* IE11
* Safari 11.0.3
* Firefox 58.0.2
* Chrome  64.0.3282.186 
* Microsoft Edge 40.15063.0.0
=> Fix Download for IE11

community.md
Signed-off-by: Eric Stoekl <ems5311@gmail.com>
I would like to add this post on adding SSL to your deployment of Faas-Netes on Azure AKS to the community.md file.
Adds an entry for Azure AKS Part 2 to community.md
=> Adding Azure AKS Part 2 to community.md

guide/deployment_swarm_arm.md
Update the ARM deployment guide now that full templates are provided thus negating the need to patch the Dockerfiles.
Updating documentation so that it matches the current state of the the product.
Fixes #614
- [ x ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Spellchecker and proof read
=> Remove patching references from ARM deployment guide

docker-compose.yml
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
compose file is formatted with spaces except for that line
=> Replace tabs with spaces

docker-compose.yml
Update queue-worker version to latest 0.4.3 in docker compose
Raised by @alexellis
=> Update queue-worker version

community.md
Added pycon talk to 2018 events and added a new sample function
Keep community guide up-to-date
N/A
=> updated community guide

sample-functions/NodeInfo/Dockerfile, sample-functions/NodeInfo/Dockerfile.arm64, sample-functions/NodeInfo/Dockerfile.armhf
Update the NodeInfo sample function to use latest
watchdog version (0.7.7) to support both GET and POST method.
tested on Mac:
```
echo -n "" | faas-cli invoke mynodeinfo --method=GET -g=http://localhost:31112
Hostname: mynodeinfo-7bd766765f-v6nhh
Platform: linux
Arch: x64
CPU count: 4
Uptime: 12325
```
```
echo -n "" | faas-cli invoke mynodeinfo --method=POST -g=http://localhost:31112
Hostname: mynodeinfo-7bd766765f-v6nhh
Platform: linux
Arch: x64
CPU count: 4
Uptime: 13675
```
=> Update nodeinfo sample function

community.md
New blog from Marcus Smallman on writing OpenFaas serverless function in
go has been added to community.md file
=> Added new blog to community.md file

watchdog/Dockerfile, watchdog/handler.go, watchdog/main.go
Moves handler code into separate file but retains same
package.
Changes watchdog to print version on start-up so that we can
grab this from logs. Version flag is also present for getting
additional information if needed from a user's published
container without running their function.
Review of previous PR for issue #632 
Local system, CI and via Docker.
=> Print version flag on every run

.travis.yml
Fix #650
Pipe the Docker registry password so that `docker login` doesn't block
=> Fix Docker Registry push

gateway/assets/index.html
I have added a CSS class that hides the element it is applied to if java script is disabled.
I have applied this to a div element containing all of the body code.
I have also added a message that is shown when java script is disabled.
Signed-off-by: Rillian Grant <rillian.grant@hotmail.com>
=> Added a message for people who don't have JavaScript enabled. (2)

TestDrive.md, docker-compose.yml, guide/deployment_digitalocean.md
This updates the gateway version to the latest 0.8.0 and faas version in markdown docs
Does not touch fwatchdog
Raised by @alexellis
=> Update gateway version to 0.8.0

.DEREK.yml
Adding my github username to DEREK.yml
so that I can help triage UI issues
Signed-off-by: John Callaway <john@1north.com>
Adding my github username to DEREK.yml
so that I can help triage UI issues
Adding my github username to DEREK.yml
so that I can help triage UI issues
I have not done any testing.
=> Add my username to DEREK.yml

api-docs/swagger.yml, gateway/server.go
Add health and info endpoints as described in #689 
Fixes issue #689 by enabling /healthz and /system/info, see
swagger for more details.
Tested by accessing the two new endpoints
=> Add health and info endpoints

community.md
Signed-off-by: Keiran Smith <contact@keiran.scot>
Add links to
- [Building a Serverless Microblog in Ruby with OpenFaaS – Part 1 ](https://keiran.scot/2018/05/18/faasfriday-serverless-microblog/)
- [OpenFaaS Swift Template](https://github.com/affix/openfaas-swift-template)
- Extends community.md
=> Add Ruby Microservice Blog post and swift template

community.md
Add Alexs' Docker London event to COMMUNITY.md
n/a
Trivial doc change
=> Add Alexs' Docker London talk to COMMUNITY.md

community.md
Added our experience with serverless computing and speeding up Iconscout with OpenFaaS
Signed-off-by: Tarun Mangukiya <tarunmangukiya@hotmail.com>
=> Added Blog post in community.md

community.md
Signed-off-by: Robbie Page <rob@rorpage.com>
Add blog post to `community.md`
N/A
N/A
=> add K8s post to community.md

.DEREK.yml
Signed-off-by: Keiran Smith <contact@keiran.scot>
add myself to Derek maintainers
=> Add affix to derek maintainers

community.md
Add Meetup event to community.md file
Discussed on Slack
N/A
=> Add OpenFaaS meetup to community file

community.md
Add Birmingham DevOps even to community.md
Add upcoming event
Not a code change
community.md change
=> Add Birmingham DevOps even to community.md

community.md
Signed-off-by: Eric Stoekl <ems5311@gmail.com>
Add the Docker Seattle meetup with link to the community.md file.
=> Add Docker Seattle meetup to community.md

community.md
This changes to add Bangalore meetup details to community file.
=> Added bangalore meetup details to community file

.DEREK.yml
This changes to add viveksyngh to .DEREK.yml to manage github issues
using derek.
=> Added viveksyngh to maintainers list

community.md
Signed-off-by: Steven Tsang <tsangste@gmail.com>
Add shirley meetup details to the community file.
=> Add shirley meetup details to the community file

community.md
Add Cloud Native meetup event to community doc.
n/a
=> Add Cloud Native Glasgow event

community.md
AWS Fargate provider added as community project
Update to community.md
=> AWS Fargate provider added as community project

community.md
2 new blog posts from Alex Ellis and Steven Kang added to the community.md file
No issue needed for adding blogs to the community file
=> Add 2 new blog posts to community.md

.DEREK.yml
Change `iyovcheva` to `ivanayov` after username has been changed
=> Update .DEREK.yml with username

gateway/assets/img/icons/outline-file_copy-24px.svg, gateway/assets/index.html, gateway/assets/script/bootstrap.js, gateway/assets/style/bootstrap.css
This change adds a function URL field to the UI and a 'copy to clipboard' button next to it. If the browser does not support the copy command, the copy icon will be hidden.
The following is how it looks like when the browser doesn't support clipboard copy.
https://github.com/openfaas/faas/issues/765
1. Click a function
2. Click the copy icon next to the URL field
3. Check if the URL was copied by pasting it somewhere
Tested browsers
=> Added function url field and copy action to the UI

gateway/plugin/external.go
Updated gateway to accept 202 as valid response code for
/system/scale-function/<function> along with 200.
Fixes: https://github.com/openfaas/faas-netes/issues/245
raised by @alexellis  https://github.com/openfaas/faas-netes/issues/245
I have tested for kubernetes on Docker for Mac.
=> Accept 202 as valid code for /system/scale-function/<function>

guide/kong_integration.md
With this commit i extend the kong docs to add routing for
async invocation of functions.
Kong guide did not include async routing so i added the way to enable it.Also increased
the postgress version from 9.4 to 9.5 since 9.4 is outdated
It references https://github.com/openfaas/faas/issues/766.
Was able to invoke figlet async function with ```curl localhost:8000/function/figlet -d 'hello world'```.
=> Add route for async invocation of functions in the kong guide

.DEREK.yml
I am adding myself to maintainers in .DEREK file
Add myself to list of maintainers in .DEREK
=> Add myself to list of maintainers in DEREK

README.md
This commit adds link to offical docs and new blog site to README.md
file.
=> Add new blog and docs site to README

community.md
Adding blog posts from Ajeet Raina and Mark Sta Ana
No issue raised for adding blog posts
No tests required
=> Add blog posts to community file

api-docs/swagger.yml
Changes:
- Increased version to reflect the latest
- Every path now is warpped in single quotes
- Added all receivable Status Codes to paths
- Made use of Definitions
- Added required annotation to fields 
Signed-off-by: Simon Pelczer <templum.dev@gmail.com>
Updated the existing swagger documentation to reflect the current implementation. It now shows all receivable status codes along with the models. Further, it displays required fields.
=> Updated Swagger Documentation

community.md
Add blog post detailing VMware CodeHouse 2018 where OpenFaaS was a major technical component.
Not tested, just a small docs change.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
=> Add blog post on VMware CodeHouse

.DEREK.yml
Addressing issue https://github.com/openfaas/faas/issues/824, added bartsmykla, LucasRoesler, s8sg, viveksyngh per https://github.com/orgs/openfaas/people, removed inactive users ovation22, cpitkin, jockdarock, itscaro
Signed-off-by: Stanton Xu <xjiefeng@gmail.com>
=> Amend Derek users in .DEREK.yml file

docker-compose.yml
I am moving gateway build version to 0.8.11
Bump up gateway version to 0.8.11
Noted above ^
N/A
=> Bump up the gateway to 0.8.11

CONTRIBUTING.md, sample-functions/AlpineFunction/Dockerfile
Update alpine function to use latest watch dog to [support testing patch](https://github.com/openfaas/certifier/pull/10)
Relates to: #815
Using  [support testing patch](certifier#10)
```
=== RUN   Test_Invoke_With_Supported_Verbs
--- PASS: Test_Invoke_With_Supported_Verbs (12.04s)
=== RUN   Test_Invoke_With_Supported_Verbs/GET
--- PASS: Test_Invoke_With_Supported_Verbs/GET (12.01s)
=== RUN   Test_Invoke_With_Supported_Verbs/POST
--- PASS: Test_Invoke_With_Supported_Verbs/POST (0.00s)
=== RUN   Test_Invoke_With_Supported_Verbs/PUT
--- PASS: Test_Invoke_With_Supported_Verbs/PUT (0.00s)
=== RUN   Test_Invoke_With_Supported_Verbs/PATCH
--- PASS: Test_Invoke_With_Supported_Verbs/PATCH (0.00s)
=== RUN   Test_Invoke_With_Supported_Verbs/DELETE
--- PASS: Test_Invoke_With_Supported_Verbs/DELETE …
```
=> Update alpine function to enable patch support

community.md
Signed-off-by: James McAfee <mcafeej@vmware.com>
Added event for meetup in Sydney for September 12th, 2018
Not Applicable
=> update to add sydney event to community listings for 2018

api-docs/swagger.yml
Adds missing annotation attribute to swagger file
=> Adds missing annotation field from swagger.yml

docker-compose.armhf.yml, docker-compose.yml, gateway/Makefile, gateway/server.go, gateway/types/handler_set.go
Refactor #843
Code-review/refactoring for #843. Closes #843.
FaaSHandlers has had info and query handlers added to its list
of types for consistency.
Secrets added to queue-worker component ready for next PR.
=> Code-review/refactoring for #843 (basic auth enhancement)

community.md
Added Cerner Engineering Blog post found via Twitter: https://twitter.com/CernerEng/status/1037366052001394689
=> Added Cerner ShipIt blog post to community

community.md
Add blog post in Chinese to community.md file 
Also, adjusted the previously added Chinese video to
retain the Chinese title and placed it in order
=> Add Chinese blog post to community

docker-compose.armhf.yml, docker-compose.yml
Bumping gateway to latest 0.9.2 release for docker-compose.yml
and docker-compose-armhf.yml files
Bumped up gateways to 0.9.2 for armhf and normal compose files
Requested
N.A.
=> Bump gateway to 0.9.2 for docker-compose and docker-compose-armhf

docker-compose.armhf.yml, docker-compose.yml
=> Bump queue-worker to v0.5.2

community.md
Added my blog post to the community page
=> Add vertx/graalvm post

community.md
This change adds link to the table of contents on the
community.md file as well as adding links to return to top
from the headers.
The community file is becoming very large (:tada:) and difficult to navigate easily.
This adds links to the table of contents to quickly jump to a section and adds links under each of the headers back to the top so it's easier to get back to the table of contents and jump to another section
Rendered on Github
=> Add TOC links to community.md

community.md
This PR adds link to the DigitalOcean OpenFaaS tutorial.
=> community: add link to digitalocean tutorial

contrib/publish-armhf.sh
Proceed with building the image only if it's not already available.
=> ARMHF publishing script - check if the Docker image is already present.

community.md
Signed-off-by: Frank Pommerening <frank@pommerening-online.de>
Add event DevOpenSpace to community page
- [] My code follows the code style of this project.
=> Add event DevOpenSpace to community

community.md
Discovered this blog post via Twitter and adding it to the community file
N/A
N/A
=> Add blog post from Keyu on serverless R

docker-compose.armhf.yml, docker-compose.yml
=> Update queue worker version to 0.5.3

community.md
Add OpenFaaS terraform provider to the community.md
=> Add terraform provider to community.md

community.md
Add Japanese events related to ServerlessConf Tokyo and a blog post to community.md file.
=> Add Japanese events and blog posts

community.md
Signed-off-by: Patricio Diaz <padiazg@gmail.com>
Added entry for KubeCon+CloudNativeCon 2018 Event
=> Added KubeCon+CloudNativeCon 2018 Event

community.md
Add PHP Scotland and VMUG Ireland events to community
n/a
Visual inspection of rendered markdown
=> Add PHP Scotland and VMUG Ireland events to community

docker-compose.armhf.yml, docker-compose.yml
Bump versions to faas-swarm:0.4.4 and queue-worker:0.5.4
=> Bump versions for faas-swarm and queue-worker

sample-functions/business-strategy-generator/handler.go, sample-functions/business-strategy-generator/vendor/github.com/nishakm/strategy_generator/README.md, sample-functions/business-strategy-generator/vendor/github.com/nishakm/strategy_generator/main.go, sample-functions/business-strategy-generator/vendor/github.com/nishakm/strategy_generator/pkg/generator.go, sample-functions/stack.yml
Adds business strategy sample function
=> Add sample function

contrib/publish-armhf.sh
Add openfaas-operator to the ARMHF build script
Tested it by running the script on the RPi board
=> Add openfaas-operator to the ARMHF build script

community.md
Hello, I added a blog post https://k33g.gitlab.io/articles/2018-10-20-OPENFAAS.html
It's a kind of quick start
=> Add a blog post

community.md
Adding a blog post from Saurabh Londhe for deploying a Python app with OpenFaaS
=> Add blog post from Saurabh Londhe

community.md
Add blog post from Philippe Charrière about using Express.js with OpenFaaS discovered via Twitter: https://twitter.com/k33g_org/status/1056545373005770752?s=19
=> Add blog post from k33g

gateway/Dockerfile, gateway/Dockerfile.arm64, gateway/Dockerfile.armhf, gateway/handlers/alerthandler.go, gateway/handlers/alerthandler_test.go, gateway/handlers/scaling.go, gateway/plugin/external.go, gateway/plugin/external_test.go, gateway/scaling/function_cache.go, gateway/scaling/function_cache_test.go, gateway/scaling/function_scaler.go, gateway/scaling/range.go, gateway/scaling/scaling_config.go, gateway/scaling/service_query.go, gateway/server.go
Extract package for scaling from zero
Extracting this package means it can be used in other components
such as the asynchronous nats-queue-worker which may need to
invoke functions which are scaled down to zero replicas.
Tested on Docker Swarm for scaling up, already scaled and not
found error.
=> Extract scaling from zero into a package

community.md
Signed-off-by: TPei t.s.peikert@gmail.com
I added a link to my crystal template repository
=> Add link to Crystal Template

community.md
=> Add banaglore kubernetes meetup event

community.md
Adding Meetup event scheduled for this month at the Cloud Austin Meetup group
=> Add Austin meetup event to community file

community.md
Adding blog post from golem.de (in German) to community file
N/A
=> Add blog post from golem.de to community

.gitignore, .travis.yml, ci/hashgen.sh
This change mirrors the method employed on
faas-cli to generate and deploy the sha256 hash for each flavour of the current watchdog.
Issue #955 suggested that the watchdog binaries should have associated sha256 files to help assure the veracity of the built artefacts.  
Ran CI on rgee0/faas and created a release.  Validated that sha256 files were produced & that they correspond with the respective watchdog binary.
```
$ curl -sSL https://github.com/rgee0/faas/releases/download/0.0.5/fwatchdog > fwatchdog
$ curl -sSL https://github.com/rgee0/faas/releases/download/0.0.5/fwatchdog-arm64 > fwatchdog-arm64
$ curl -sSL https://github.com/rgee0/faas/releases/download/0.0.5/fwatchdog-arm64.sha256 > fwatchdog-arm64.sha256
$ curl -sSL …
```
=> Add sha256 hashgen for watchdog to ci config

community.md
Signed-off-by: Laurent Grangeau <laurent.grangeau@gmail.com>
=> Add DevOpsDDay and Capitole du Libre conferences from France

docker-compose.yml
It should be configured to true by default and disabled by choice.
=> Fix scale from zero to be true by default

community.md
A talk on IstaCon, Sofia, workshop on OpenFest, Sofia, and a lightning talk during the same event are added to the events list
=> Add OpenFest and IstaCon events in November

community.md
Signed-off-by: marcus-smallman <marcussmallman@live.co.uk>
Updated the community file with the csharp mongodb template.
=> Add csharp mongodb template to community file

docker-compose.armhf.yml, docker-compose.yml
- Update the fass-swarm version to 0.5.0
faas-swarm just released version 0.5.0 https://github.com/openfaas/faas-swarm/releases/tag/0.5.0, this PR keeps the faas repo insync with the latest version of swarm. 
**Note** @alexellis this assumes that a `0.5.0-armhf` tag will be pushed soon
Tested by deploying with my local Docker swarm and then successfully deploying a function using the UI.  I then set `direct_functions` to `false`, redeployed openfaas and then redeployed a function successfully.
=>  Bump the faas-swarm version in the compose yml

gateway/Dockerfile, gateway/Dockerfile.arm64, gateway/Dockerfile.armhf
Update the build image to 1.10.4
Verified that for x86 and armhf it builds successfully. Not verified yet for arm64.
=> Update gateway to golang:1.10.4

community.md
Signed-off-by: TPei <t.s.peikert@gmail.com>
I'd like to add a blog post I wrote on using Crystal with OpenFaaS to the community.md file
=> add link to blog describing how to write serverless crystal functions

gateway/assets/script/bootstrap.js
- Update the function image value during the `refreshData`
- Apply vscode default JS/TS formatting
Please start your review with the commit 3fe8267 this contains the actual implementation change
The second commit is purely formatting changes.
Resolves #990 
This manually tested in a local deployment
0. update docker-compose to mount the local assets folder,  adding this to the `gateway` definition
```yaml
volumes:
- "./gateway/assets:/home/app/assets"
```
1. deploy to docker swarm using the `./deploy_stack.sh`
2. deploy a project using `faas-cli up -f stack.yml --tag=sha`
3. open the function details in the ui
4. modify the function, commit, and redeploy using `faas-cli up -f stack.yml --tag=sha`
5. observe that the Image field updates to match the new git sha
=> Fix fnc image name in the ui

gateway/Gopkg.lock, gateway/Gopkg.toml, gateway/vendor/github.com/gorilla/mux/.travis.yml, gateway/vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md, gateway/vendor/github.com/gorilla/mux/README.md, gateway/vendor/github.com/gorilla/mux/doc.go, gateway/vendor/github.com/gorilla/mux/example_authentication_middleware_test.go, gateway/vendor/github.com/gorilla/mux/example_route_test.go, gateway/vendor/github.com/gorilla/mux/middleware.go, gateway/vendor/github.com/gorilla/mux/middleware_test.go, gateway/vendor/github.com/gorilla/mux/mux.go, gateway/vendor/github.com/gorilla/mux/mux_test.go, gateway/vendor/github.com/gorilla/mux/old_test.go, gateway/vendor/github.com/gorilla/mux/regexp.go, gateway/vendor/github.com/gorilla/mux/route.go, gateway/vendor/github.com/gorilla/mux/test_helpers.go
- Update  and vendor gorilla 1.6.2
See #945 
Testing is in progress, I will test it manually by building a new gateway and then validating that the UI behaves as expected.  Similarly, I will deploy, invoke, and then remove a function using the CLI
=> Bump gorilla mux to 1.6.2

community.md
Adds the Serverless Architecture Conf in The Hague, April 2019
Visual inspection of local dev site.
=> Add Serverless Architecture Conf April 2019 talk

community.md
Found this blog post via [Twitter](https://twitter.com/befreax/status/1079135654183948289) and adding it to the community file (probably last in 2018!)
N/A
=> Add tracing your functions blog post

community.md
=> Adding more blogs and a 2019 event found via Twitter

community.md
adds docker nl event and paris cncf
=> Community update: adds docker nl event and paris cncf

community.md
Signed-off-by: Daniel Llewellyn <daniel@bowlhat.net>
This PR adds my post on medium to the community.md file.
Alex suggested that I do this, so I did :-) more publicity for the win!
I used VSCode's "Markdown preview" feature to test that my changes to community.md are properly formatted.
=> Add diddledan's medium post to community.md

gateway/assets/script/bootstrap.js, gateway/assets/templates/newfunction.html
This change validates manual input to the gateway UI when deploying
new functions. This is to prevent poor user experience when attempting
to deploy a function manually from the UI.
The validation check on the function name is the same pattern that
is used in the CLI to ensure that when the deploy button is pressed,
the function will not fail validation.
Fixes #901 
Deployed updated gateway code locally, and attempted to input good and bad input into the fields.
=> Gateway UI - validate manual input

community.md
Adding blog post about Serverless on Raspberry PI with
Docker Swarm and OpenFaaS by Mathias Deremer in the
Blog posts and write-ups 2019
Adding blog in the `community.md` file.
Adding article with original french title [Serverless sur Raspberry PI avec Docker Swarm et OpenFaas : partie 1 – Installation d’OpenFaas](https://blog.ineat-conseil.fr/2019/01/serverless-sur-raspberry-pi-avec-docker-swarm-et-openfaas-partie-1-installation-dopenfaas/) from Mathias Deremer-Accettone.
It was requested
N.A.
=> Add article from ineat-conseil

community.md
Signed-off-by: Bart Smykla <bsmykla@vmware.com>
=> Fixed sorting in 2019 events + added my talks

docker-compose.armhf.yml
Signed-off-by: Rishabh Gupta<r.g.gupta@outlook.com>
Updating docker images for armhf OpenFaas deployment to latest versions.
This change updates the docker images to latest versions.
- openfaas/gateway:0.9.10-armhf -> openfaas/gateway:0.9.14-armhf
- openfaas/faas-swarm:0.5.0-armhf -> openfaas/faas-swarm:0.6.1-armhf
- openfaas/queue-worker:0.5.3-armhf -> openfaas/queue-worker:0.5.7-armhf
1. Update the images in docker-compose.armhf.yml
2. run `docker stack deploy func -c ./docker-compose.armhf.yml`
3. Openfaas Gateway should be available at port 8080
4. The function invocations are reset, so try to invoke functions and see the count going up
=> Updated armhf images in docker-compose.armhf.yml

docker-compose.arm64.yml
Used for tracking the docker compose file updates for ARM64. Was part from https://github.com/openfaas/faas/pull/995
Not tested yet. Will cover it though once the environment is ready.
=> Update the ARM64 docker compose file

docker-compose.arm64.yml
Update the command line arguments for Alertmanager
=> Fix Alertmanager command line arguments

docker-compose.arm64.yml
Also refactored a bit the file to have the same layout as the x86 one. 
Perhaps we can try to keep the layout for the three architecture as close as we can, so applying changes is easier and it will look cleaner overall.
=> Update the use of basic-auth secret

community.md
Signed-off-by: Chad Taylor <taylor.thomas.c@gmail.com>
This PR adds a link to my blog post introducing a Clojure template for OpenFaaS.
Alex asked for this change in Slack.
N/A
N/A
=> Add blog post introducing openfaas-clojure-template

contrib/alertmanager-arm64/0.15.0/Makefile, contrib/alertmanager-armhf/0.15.0/Makefile, contrib/prometheus-arm64/2.6.1/Makefile, contrib/prometheus-armhf/2.6.1/Makefile
=> Makefiles updated for Alertmanager and Prometheus for ARMHF/ARM64

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
This PR is tested locally(see below), but will be blocked until the following images are available:
It also fixes an issue on ARMHF where the alertmanager is failing to replicate(config option)
* Built the pending images locally via `publish-arm.sh`
* Verified that OpenFaaS is deployed successfully
* Verified that a function can be created and called as expected.
=> Reconcile Docker Compose Files and update image versions for all platforms

community.md
- Add link to 2019 blog post table
Previewed rendered markdown on github
=> Add link to of blog on multi-file py functions in the community page

community.md
Add a new blog post named "Evaluation of Serverless Technologies at
Jet".
Signed-off-by: Khalid Hasanov <xalid.h@gmail.com>
Adding a new blog post link into community.md as requested by @alexellis 
- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
=> A new blog post about serverless evaluation

contrib/prometheus-arm64/2.7.0/Dockerfile, contrib/prometheus-arm64/2.7.0/Makefile, contrib/prometheus-arm64/2.7.0/README.md, contrib/prometheus-armhf/2.7.0/Dockerfile, contrib/prometheus-armhf/2.7.0/Makefile, contrib/prometheus-armhf/2.7.0/README.md
=> Add Prometheus 2.7.0 for ARMHF/ARM64

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
Deployed the stack and triggered one of the test functions.
=> Bump Prometheus to 2.7.0

community.md
Adding blog post by Richard Gee in the official
openfaas site with title RIde the SErverless Wave with
DigitalOcean's One-click Droplet
Adding blog post by Richard
N/A
=> Add blog post by Richard

community.md
=> Adds FaaS comes to Fargate blog post to community.md

sample-functions/README.md
I just changed a small typo in the example functions readme.
gif-maker instead of git-maker
Not tested
=> corrected typo in example function list in readme

community.md
Adding not so faas webinar to the 2019 events
in community.md
Adding event
Adding Not so FaaS, Hacker webinar to the 2019 events in the `community.md`
N/A
=> Add Not so FaaS webinar

docker-compose.yml
=> Bump Prometheus to 2.7.1

community.md
Adding talk in event tab in Lyon France by
Laurent Grangeau along with blog by Leon Sriger
Adding blog post and event
Adding blog post Artifactory and OpenFaaS – Containers Everywhere! by Leon Stigter and event in Lyon France Knative, OpenFaaS, Kubeless : la guerre des frameworks serverless est lancée ! by Laurent Grangeau
N/A
=> Add event and blog in community file

community.md
Add link to community.md
Trivial text based change
=> Add link to Making Legacy Legendary video to community.md

api-docs/swagger.yml
Signed-off-by: Rishabh Gupta<r.g.gupta@outlook.com>
Previous Spec was flawed as it showed that the response model was
```
[
{
"name": "aws-key",
"value": "changeme"
}
]
```
Changed the model to match what is returned
=> Update /system/secrets API Spec

docker-compose.yml
=> Bump queue-worker version to 0.7.1

community.md
Signed-off-by: Sajeetharan Sinnathurai sajeefx@gmail.com
Added a link to blogpost about on "Building microservices on azure platform with OpenFaas"
N.A
=> Add blog post Build your serverless functions with OpenFaas on Azure

.DEREK.yml
Signed-off-by: Rishabh Gupta<r.g.gupta@outlook.com>
=> Add zeerorg to .DEREK.yml maintainers list.

community.md
Adding blog by Tim Levett
Adding blog post OF on Docker Swarm on RPi by Tim Levett
Requested
n/a
=> Add OF on Docker Swarm on RPi blog

community.md
Adding Serverless with OPenFaaS article
to community file
Add blog post to` community.md`
Requested
N/A
=> Add Serverless with OpenFaaS article

community.md
Adding blog Favorite Tools - OpenFaaS by
Markus Fischbacher
Adding article `Favorite Tools - OpenFaaS` to `community.md`
Requested
N/A
=> Add favorite tools - OpenFaaS blog

community.md
Adding event in Nantes, France
Adding event to community file
Requested
N/A
Addition to community file
=> Add SFEIR Lunch event

community.md
=> Add Spotinst blog post

prometheus/k8s.prometheus.yml, prometheus/prometheus.yml
=> Update scrape port for prometheus to 8082

community.md
Add my upcoming Kubecon 2019 talk to the community.md 
https://kccnceu19.sched.com/event/MPZM/merging-quickly-in-a-cloud-native-world-lucas-roesler-contiamo
(also removes to trailing spaces)
=> Add kubecon talk from lucas to community

.DEREK.yml
Signed-off-by: Matias Pan <matias.pan26@gmail.com>
Add my github handle to DEREK.yml.
=> Add matipan to DEREK

community.md
Adds the upcoming speaking slot at this years BelFOSS conference at Queens University Belfast.
n/a
=> Add BelFOSS 2019 conference to events

community.md
Adding IT depends event to the community.md
in Events in 2019 section
Requested
N/A
Article adding
=> Add IT Depends event

community.md
Add introductory talk at event in Mexico.
=> Add introductory talk at event in Mexico.

community.md
Add PHP Shropshire event on 2nd May to community.md
=> Add PHP Shropshire event

gateway/Dockerfile.arm64, gateway/Dockerfile.armhf, gateway/assets/script/funcstore.js
Moved to functions.json instead of store.json
Fixes issue #1145 
The pull request has been pushed to zeerorg/gateway:new_store docker image.
In the `docker-compose.yml` change the gateway image from `openfaas/gateway:v0.13.0` to `zeerorg/gateway:new_store` then deploy to test
=> Use functions.json instead of store-arch.json

community.md
Added a new blog entry to the community file
Added a new blog entry to the community file
Signed-off-by: Erwin Staal erwinstaal@gmail.com
=> Added a blog to the blog section in community.md

community.md
Added teqnation talk to the events table
Added my teqnation talk to the events table
tried to build faas local and it stil compiles :-)
local latop
=> Added teqnation talk the events table

community.md
Added a new blog entry to the community file and fix then name of a previous one
Added a new blog entry to the community file and fix then name of a previous one
Signed-off-by: Erwin Staal <info@staal-it.nl>
=> Added a new blog entry to the community file

docker-compose.armhf.yml, docker-compose.yml
Update faas-swarm to latest release 6.2 in docker-compose
=> Updates faas-swarm to current release 6.2

community.md
Signed-off-by: Matias Pan <matias.pan26@gmail.com>
I wrote a blog post and a couple of OpenFaaS Templates and I wanted to share them with the community.
=> Add blog post and openfaas templates

community.md
Adding event in Seattle, USA about blockchain with openfaas
and docker by Dean Shelton
Add event in community.md file
Adding event in Seattle about blockchain with Docker and OpenFaaS
N/A
=> Add Blockchain as a service event

community.md
Discovered blog post via Twitter and added with other posts to community file
Read through blog post. Good information, as well as valid links to OpenFaaS sources
=> Add OHV blog post to community

community.md
👋  If you guys want it - contribution to community example repositories. Providing simple bikeshare function that integrates with General Bikeshare Feed Specification (GBFS) systems. Can be used as inspiration for Bikeshare apps running on openfaas.
Want to spread love for openfaas with inspirational example repository bikeshare users can build on.
Linked repo in daily use. 
Community.md documentation.
=> Added GBFS bikeshare integration function for example repos

community.md
=> Adds ContainerDays EU and terraform provider talk

community.md
Adding event OpenFaaS - mit Docker einfach Serverless by
Frank Pommerening in Ratingen Germany to community file
Adding event to community.md file
Requested
N/A
=> Adding event in Ratingen Germany

community.md
Adding event OpenFaaS - mit Docker einfach Serverless
to the Events in the community.md file
Adding event to the community file
Adding event `OpenFaaS - mit Docker einfach Serverless` to community.md file
=> Adding event in community file

community.md
Adding the recording of the Dockercon OpenSource Summit: Serverless
as well as the code.talks Live Example to the community file
N/A
=> Add 2 videos to community file

community.md
Signed-off-by: Carson Anderson <ca@carsonoid.net>
=> Add ContainerWorld presentation to 2019 events

community.md
Signed-off-by: andmos <andreas.mosti@gmail.com>
Blogpost about writing a Slack-bot for integrating with GBFS bikeshare systems. Contains a couple of openfaas functions as examples.
Committing this to help spread my love for OpenFaaS and micro-mobility.
Blogpost links to code repository.
=> Added link to blogpost about running bikeshare functions with openfaas

community.md
=> Add missing blogs to community file

community.md
Signed-off-by: Kevin Turcios <kevin_turcios@outlook.com>
=> Add blog post on OpenFaaS/K8s client

community.md
Adding a talk including OpenFaas
=> Add talk @ GoWayFest

docker-compose.yml
I have tested this change on my local cluster. 
1. Updated the gateway image to `0.13.91
2. Deployed openfaas on my local swarm cluster with basic auth
3. Deployed figlet function from store.
4. Invoke figlet using UI
=> Update gateway to 0.13.9 for swarm

gateway/assets/img/icons/baseline-add_circle_outline-24px.svg, gateway/assets/img/icons/baseline-expand_less-24px.svg, gateway/assets/img/icons/baseline-expand_more-24px.svg, gateway/assets/img/icons/baseline-remove_circle_outline-24px.svg, gateway/assets/script/bootstrap.js, gateway/assets/style/bootstrap.css, gateway/assets/templates/newfunction.html
Adding additional inputs for Environment variables, Secrets,
Labels, and annotations so that more advanced functions can
be deployed through the UI.
This also allows more advanced functions to be provided via
the store. Allowing modification to secret values, and
environment variables which will allow functions like a
Slack Bot function to be deployed through the store adn
configured with an environment variable
Example with the field areas collapsed (default view):
Example with the field areas expanded (by clicking on the section title ie: "Environment Variables"):
Finally, with all of the fields filled in, showing that multiple values can be added for each group:
Now, selecting a function from the store, and switching over to the …
=> Add additional fields to the UI

community.md
Signed-off-by: Ron Rivera <roncrivera@gmail.com>
Add new blog post to community file.
=> Add new blog post.

community.md
This adds some additional videos from previous talks
at Dockercon that have not yet been included
Discussions with Alex revealed these 2 videos from previous Dockercon talks were not yet included in the community file
...watched the videos :smile:
=> Add Dockercon videos to community

community.md
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>
Added Belo Horizonte Meetup organized by @pasimoes to community file.
=> Added Belo Horizonte Meetup

community.md
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>
Changed event name from "Serverless Functions Frameworks : OpenFaaS e Fn Project" to "Serverless Functions Frameworks : OpenFaaS Day" as suggested by a comment in #1236 by @pasimoes
=> Changed event name

community.md
=> Updated speaker names and event url

api-docs/swagger.yml
Signed-off-by: gabrielsson <max.gabrielsson@gmail.com>
The documentation for async-function pointed to
the old faas/guide and should be to docs.openfaas.com
#1250
=> Fix async-function doc broken link in swagger

community.md
Add event for Chicago Kubernetes meetup
Add writeup for On-Premises Serverless Computing found via Twitter: https://twitter.com/gmolto/status/1148554459313770496
N/A
=> Add event and writeup to community

community.md
Add an interview with Alex and The New Stack discussing Serverless 2.0
Discussed with Alex via Slack
N/A
=> Add Alex The New Stack interview

api-docs/swagger.yml, gateway/Dockerfile, gateway/build.sh, gateway/handlers/infohandler.go, gateway/tests/integration/infohandler_test.go, gateway/types/inforequest.go
With this change `/system/info` endpoint is going to give information about the platform architecture it is running on (arm64, armhf, x86_64)
Closes #1148
Deployed faas locally and checked endpoint http://127.0.0.1:8080/system/info :
```
"provider":{"provider":"faas-swarm","version":{"sha":"223e228eff7daa82c69214bc21b7b25ea188f7b4","release":"0.6.2"},"orchestration":"swarm"},"version":{"sha":"","release":"dev"},"arch":"amd64"}
```
=> Add architecture to /system/info endpoint

community.md
As a request from OpenFaas in [this tweet](https://twitter.com/openfaas/status/1153942713882095616) I'm adding the Serverless Week event to the community events in 2019.
Not applicable
=> Add Serverless Week as community event

community.md
Added blog post from upnxtblog created in Oct 2018, try to find the correct information about the author.
In the preview and click on the links
=> Added blog post from karthik @ upnxtblog

docker-compose.arm64.yml, docker-compose.armhf.yml
=> [WIP] Update armhf and arm64 images

community.md
Signed-off-by: Andreas Muttscheller <andreas.muttscheller@codecentric.de>
Added the blog post to the community file.
Checked community.md on my branch
=> Add  'Building your own serverless functions with k3s and OpenFaaS on Raspberry Pi' blog post

community.md
Signed-off-by: Qolzam <amir.gholzam@live.com>
Added the blog post to the community file.
I have checked the change in my repo. The change is only on community.md file.
=> Add blog post by Amir Movahedi

community.md
=> Adds techin.finance event to community.md

watchdog/README.md
=> Fix some grammar errors in the watchdog/README.md file

CONTRIBUTING.md, README.md, TestDrive.md
Discovered a couple of links that could be updated to prevent errors or confusion
The issue was originally raised in this repo, but moved to the docs repo as that is where the issue author had found the errors. In my attempt to locate the errors, I found a few places where the links in this repo could also be updated
Reference issue: https://github.com/openfaas/docs/issues/167
Clicking through the links locally to verify they all function without error and go to the expected page
=> Update various links to prevent errors

community.md
Signed-off-by: Saiyam Pathak <saiyam911@gmail.com>
Description
Added all the talks from the September Openfaas Event Happening at Microsoft Office, Bangalore, India
How Has This Been Tested?
Changed only the community file
Checklist:
=> Added Openfaas September Event happening at Bangalore

docker-compose.arm64.yml, docker-compose.armhf.yml
This change adds `auth_proxy_url` & `auth_proxy_pass_body` to the two ARM compose files so as to mirror the config of the x86_64 compose file.
User reported issue
Upon investigation it was found that the two docker-compose files for ARM based systems were not configured to pass the auth_proxy variables through to the gateway at deploy time.  This was causing an error in the gateway which would manifest in the CLI and UI as: `ExternalAuthHandler: Get : unsupported protocol scheme ""`.
Tested on Pi3.
```sh
export OPENFAAS_URL=http://192.168.0.30:8080
$ echo -n 9154582228ff5b54d411ff62f572e9361d8b5889a7bcbb651ed217d504f064a0 | faas-cli login --username=admin --password-stdin
Calling the OpenFaaS server to validate the credentials... …
```
=> Add auth proxy env-vars to gateway for ARM

community.md
Add link to a blogpost about OpenFaas development with Okteto
Keep community links up to date
=> Add link to "How to develop a serverless app with OpenFaas and Okteto"

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
This commit updates prometheus and alertmanager version to use
multi-arch images. Prometheus is updated to v2.11.0 and alertmanager is
updated to v0.18.0
This has been tested on Docker for Mac. 
By running the below command to generate the load and then validating the alert manager alert, prometheus metrics and number of replicas of service.
```
for i in {0..10000};
do
echo -n "Post $i" | faas-cli invoke go-echo && echo;
done;
```
After making 8K requests
After I stopped making requests.
Prometheus metrics. 
Alert manager alerts.
=> Update prometheus and alertmanager images

.DEREK.yml
Signed-off-by: Jonatas Baldin <jonatas.baldin@gmail.com>
Add myself to `.DEREK.yml`! Thanks @alexellis ✨
=> Add jonatasbaldin to .DEREK.yml

community.md
Adds GOTO copenhagen 2019 conference talk
=> Adds goto; copenhagen

community.md
This PR adds an entry for the openfaas-powershell-polaris template to the Projects, Samples, and Use Cases section of this document.
=> Add openfaas-powershell-polaris template

community.md
Add Unlocking your serverless functions with OpenFaaS for AI chatbot projects presentation to the .community.md
We need to add this presentation for #events-in-2019
Signed-off-by: Sergio Méndez <sergioarm.gpl@gmail.com>
=> Add Oscon 2019 OpenFaaS slides

community.md
Signed-off by: Josh Michielsen <github@mickey.dev>
I wrote a blog post on Getting Started with OpenFaaS.
=> Add my new blog post

community.md
Signed-off-by: Josh Michielsen <github@mickey.dev>
=> Fix event order

community.md
=> Add PyCon india workshop to community events

community.md
Migrate from Lambda to OpenFaaS blog post on openfaas.com
Discussed on OpenFaaS team meetings and on Slack
Several reviews on the blog post PR. 
For this change, rendering the preview of the markdown in VSCode
=> Add blog post from burtonr

community.md
Add link to The OpenFaas Communtiy Call held in 02-August-2019
=> Add link to The OpenFaas Communtiy Call

community.md
Signed-off-by: Ruan Bekker <rbekker87@gmail.com>
We can close https://github.com/openfaas/faas/pull/1352 in favor of this one.
Add migration of lambda to openfaas function.
=> Add migration blog post

sample-functions/MarkdownRender/Dockerfile, sample-functions/Nmap/Dockerfile, sample-functions/WebhookStash/Dockerfile
My primary purpose was to have nmap run as non-root user.  This relates to #1167 
My primary purpose was to have nmap run as non-root user.  
This relates to #1167 
The reason for the additional change was that it was suggested in the comments of the same issue.
I built the Docker image via `docker build`
I then ran it via `docker run` to ensure it would run the command properly.
Finally, I pushed the image to Docker and used it in my local openfaas environment.
=> Update nmap, MarkdownRender, and WebhookStash Sample Functions

auth/basic-auth/Gopkg.lock, auth/basic-auth/Gopkg.toml, auth/basic-auth/vendor/github.com/openfaas/faas-provider/auth/basic_auth.go, auth/basic-auth/vendor/github.com/openfaas/faas-provider/auth/credentials.go, gateway/Gopkg.lock, gateway/Gopkg.toml, gateway/vendor/github.com/openfaas/faas-provider/auth/basic_auth.go
https://github.com/openfaas/faas/issues/1355
Tested with `dep ensure`
=> Updated basic auth plugin faas provider

community.md
Added 2 upcoming meetup events for October
Discussed in Slack, discovered on Twitter
Houston (17 Oct): https://twitter.com/HouTechEvents/status/1184570974085222400?s=19
Grenoble (24 Oct): https://twitter.com/k33g_org/status/1184406881269362688?s=19
Viewed the event page to confirm event is scheduled and attendees have RSVP
=> Add 2 events in October to community file

community.md
Add 2 new blog posts discovered via Twitter:
http://twitter.com/hasdid/status/1198191220469559296
http://twitter.com/ServerlessCity/status/1198520554489352193
Communicated with Alex on Slack
Read the posts and verified the formatting with VSCode markdown preview
=> Add 2 blog posts from November

gateway/assets/index.html, gateway/assets/script/bootstrap.js, gateway/assets/templates/newfunction.html
This PR adds a namespace dropdown for the openfaas
namespaces. If a user has non-default namespaces
installed then a user can select that namespace,
view functions in that namespace, invoke them from
the UI and delete them from that namespace.
closes #1379 
#1379 
Adding this allows a user to see, delete and invoke functions in another opoenfaas controlled namespace.
This PR does not add the ability to create a fn in that namespace, That can be added in a future PR
<br>
<br>
NS-Dropdown
<br><br>
Different OF Namespace selected
<br><br>
Function in another namespace has its Ns appended to the url
<br><br>
Invoked function, showing it works 
<br><br>
default namespace selected
Deployed to my OpenFaaS instance and manually tested.
- [] I …
=> Add Namespace Dropdown to Gateway UI

community.md
I wrote blog post about OpenFaaS templates, which I'd like to add to
community page.
Signed-off-by: Martin Heinz <martin7.heinz@gmail.com>
Added line with link to my blog post to table in community.md
Spoke with Alex on Twitter
Verified the link was functional and previewed the markdown rendering with Goland.
=> Add link to blog post

CONTRIBUTING.md
Small change to markdown file
One line change in a markdown file.
=> Remove Richard from Core members list

docker-compose.yml
Updates docker-compose file to match latest releases of core components
Installed on Mac OS OpenFaaS  swarm
```
d ps -a                                                               Mon  9 Dec 15:39:24 2019
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                NAMES
996ff85d8016        ewilde/echo:latest                  "./fwatchdog"            5 minutes ago       Up 5 minutes                             echo.1.cpp0xlvx2v9fb9r9t7678tulj
802dc7302a45        ewilde/replay-schedule:latest       "./fwatchdog"            5 minutes ago       Up 5 minutes                             replay-schedule.1.j46kzmoe937mr3qnr34zkg4k5
df2aa8472eec        openfaas/faas-swarm:0.8.2           "./faas-swarm"           6 …
```
=> Update core OpenFaaS component in docker-compose

README.md
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
Update travis link from .org to .com
=> Update travis link from .org to .com

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
=> Update compose stacks to latest gateway and basic-auth

community.md
Fix a date typo in community file
(spoke to Alex on slack)
Visually
=> Fix Typo in community.md file

community.md
Add a link to a Blog post that heavily references OpenFaaS and OpenFaaS Cloud.
It talks about my contributions this year!
Additional community content
Visually
New community content
=> Add Alistair Hey Blog to community.md

community.md
Add my contributing to openfaas blogpost to the community.md file
I have added the 2020 sections too: 
Visually - see screenshots above
=> Add contributing blog to OF to community.md

community.md
Add some more blogs and the community call to the 2019 community sections
- [ x My issue has received approval from the maintainers or lead with the `design/approved` label
See screenshots. 
links have been followed from my branch's file
=> Add various posts to the community.md file

README.md
Update the example on the readme to node12 template from node10
deployed the code in openfaas (swarm) function. invoked through the web:
=> Change the node example in readme to node12

api-docs/swagger.yml
=> Update API docs for secret update

community.md
=> Update community.md with more blog posts

community.md
Adding a blog post to community.md 
Visually, 
New Post added to community file
=> Add blog to community.md Serverless made accessible

gateway/handlers/notifiers.go, gateway/handlers/scaling.go, gateway/scaling/function_scaler.go, watchdog/handler.go
=> Update log message to reduce verbosity and for consistency

auth/basic-auth/Dockerfile, auth/basic-auth/Dockerfile.arm64, gateway/Dockerfile, gateway/Dockerfile.arm64, gateway/Dockerfile.armhf
Optimizes Docker builds by copying from license-check Docker image
instead of using curl to download the tool.
Ref: #1440 
`make build` and all containers passed license-check
=> Use license-check docker image instead of curl

community.md
Add the 2020 Kubecon EU  events to the community.md file
visual and link click
=> Add our Amazing Kubecon EU 2020 events to community.md

.travis.yml, auth/basic-auth/Dockerfile, auth/basic-auth/Dockerfile.arm64, gateway/Dockerfile, gateway/Dockerfile.arm64, gateway/Dockerfile.armhf, sample-functions/BaseFunctions/golang/Dockerfile, sample-functions/DockerHubStats/Dockerfile, sample-functions/MarkdownRender/Dockerfile, sample-functions/WebhookStash/Dockerfile, watchdog/Dockerfile
Signed-off-by: Thomas Schmidt <thomaschmidt@gmail.com>
Update projects to Go 1.13 where applicable
Allow to build the various docker images used by this project to use Go-1.13. 
Fixes #1442
Using the `build.sh` script, all docker files build correctly
=> Update projects to use Go 1.13

gateway/handlers/logs_test.go
Here is a fix for `Test_logsProxyDoesNotLeakGoroutinesWhenClientClosesConnection()` in gateway/handlers`.
`testing.T.FatalF()` is a convenience function that calls `testing.T.Log()` and `testing.T.FailNow()`. From the `godoc` for `testing.T.FailNow()`:
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
This changes the test by creating an error channel to get the error variable outside of the goroutine, where it is checked after `cancel()`.
=> gateway/handlers: fix use of testing.T inside goroutine

community.md
Adds a blog post related to Faasd
=> Add faasd lxc post

community.md
Add my introdusing arkade blog post on installing OpenFaaS with arkade.
visually
new community blog post
=> Add Arkade Blog post to community.md

community.md
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
Tutorial to get OpenFaas running on top of a Kubernetes Cluster on Clear Linux OS
=> Add Tutorial by Clear Linux

community.md
Signed-off-by: Mehdi Yedes <mehdi.yedes@gmail.com>
Add blog post about running OpenFaaS with faasd on Raspberry PI
=> Add faasd on RPi blog post

community.md
Add a link for the openfaas traefik webinar that's upcoming
Visually, link checked in browser
=> Add link to Traefik webinar

deploy_stack.sh, gateway/Makefile, gateway/assets/index.html, gateway/assets/style/bootstrap.css, gateway/build.sh, gateway/push.sh
Fixes #1450
Fixes #1452
There was a no-padding class set on all of the headers, but the funcstore needed
the padding, It's been fixed.
There was also a case when using faas-netes where a single-namespace deployment was appending the namespace
to the function url, this isn't needed as the default namespace is used when no specific one is provided.
I have also added a new env var to make in the gateway directory so I can more easily build and push to my own dockerhub
repo. Building for OpenFaaS has not changed.
I have also fixed an issue in the deploy_stack.sh script where newlines (\n) were not being printed as newlines and the 
literal chars were printed instead. This makes getting the password a lot easier for swarm users.
Faas-Swarm, Faas-Netes tested.
UI deployed on swarm, no …
=> Fix Padding on UI and remove Namespace when not needed

community.md
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Updates community.md with Crossplane + OpenFaaS talk link for Serverless Practitioners Summit - Kubecon EU 2020.
Requested for organizing and tracking talks at Kubecon EU 2020.
n/a
=> Add Crossplane + OpenFaaS Kubecon Talk

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
Bumping gateway of arm armhf and x86-64 images
to 0.18.11
Manually pulled all images to verify they existed.
=> Bump gateway to newest image

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
Bumping basic auth plugin to newest 0.18.11 on
all images
Bump to newest image
Pulled manually all three images to verify they exist
=> Bump basic auth plugin to 0.18.11

.DEREK.yml
Add myself to DEREK.yml
Signed-off-by: Carlos de Paula <me@carlosedp.com>
=> Add myself to DEREK.yml

community.md
Added community events and blogs to community.md
Signed-off-by: Markus Hartmann <markush1986@gmail.com>
Added community events and blogs to community.md
=> Added community events and blogs to community.md

community.md
Add link to the Online Meetup hosted by Containous on Youtube
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
=> Add link to the Online Meetup hosted by Containous

community.md
Signed-off-by: Amir Movahedi <amir.gholzam@live.com>
Adding OpenFaaS email service blog post community.md
=> Add OpenFaaS email service blog post.

docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
Signed-off-by: Douglas Jones <d.m.jones2@gmail.com>
Closes #1484 
Updating to the latest version
Started up swarm containers on my local computers
Started Docker Swarm on my mac, brought up the UI, logged in, and deployed Colorise
=> Bumping the version numbers in docker compose files

README.md
Signed-off-by: Amal Alkhamees <amalkms5@gmail.com>
This commit update doc URL from godoc to pkg.go.dev
=> Update doc URL from godoc.org to pkg.go.dev

community.md
Adding blog post by Sean Duffy to the commynity
file
Adding blog post in community.md file
N/A
=> Add blog post RPi Kubernetes with OpenFaaS

community.md
Add blog post by Wing-Kam Wong
Signed-off-by: Wing-Kam Wong <wingkwong.code@gmail.com>
Add blog post by Wing-Kam Wong
=> Add blog post by Wing-Kam Wong

community.md
Added new blog post:
[Tracking Stripe Payments with Slack and faasd](https://myedes.io/stripe-serverless-webhook-faasd/):
=> Add new blog post: Stripe & faasd

sample-functions/stack.yml
Update stack.yml to include sample `hey` function
This has not been tested, I'm not sure how to test stacks.yml and its related integration. Let me know if that is something you'd like me to do.
=> Add hey sample function

community.md
=> Add weave online  meetup to community.md

community.md
=> Add SG virtual conference meetup to community.md

community.md
Adding Data Pipelines with OpenFaaS on K3s blog
post in the community.md
Adding https://medium.com/@yoav.nordmann/data-pipelines-with-openfaas-on-k3s-b92e97bc125b blog to community file
N/A
=> Add Data Pipelines blog

gateway/Dockerfile, gateway/Dockerfile.arm64, gateway/Dockerfile.armhf, gateway/Gopkg.lock, gateway/Gopkg.toml, gateway/handlers/forwarding_proxy.go, gateway/handlers/queue_proxy.go, gateway/handlers/queue_proxy_test.go, gateway/handlers/scaling.go, gateway/main.go, gateway/metrics/metadata_query.go, gateway/pkg/middleware/basic_auth_injector.go, gateway/pkg/middleware/basic_auth_injector_test.go, gateway/pkg/middleware/serviceauthinjector.go, gateway/plugin/external.go, gateway/plugin/external_test.go, gateway/queue/types.go, gateway/scaling/function_cache.go, gateway/scaling/function_meta.go, gateway/scaling/function_query.go, gateway/scaling/function_scaler.go, gateway/scaling/service_query.go, gateway/vendor/github.com/openfaas/nats-queue-worker/handler/nats_queue.go
Publish to multiple topics
Enables publishing to various topics according to annotations
on the functions. The function cache is moved up one level so
that it can be shared between the scale from zero code and the
queue proxy.
Covers the publishing portion of: #1330 
Unit testing added for parsing namespaces, more to follow with
e2e testing.
```bash
arkade install openfaas --clusterrole \
--set gateway.image=openfaas/gateway:0.18.16-rc5 \
--set queueWorker.image=openfaas/queue-worker:0.10.1
kubectl create ns dev
kubectl annotate ns/dev openfaas=1
```
Then:
```bash
faas-cli store deploy nodeinfo
faas-cli store deploy figlet -n dev --annotation com.openfaas.queue=slow-queue
```
Then add a queue-worker by exporting the existing one and altering its name, then run kubectl apply.
```
kubectl …
```
=> Publish to multiple topics

community.md
Adding OF with Gloo API GW blog post in community
file
Add blog https://medium.com/alterway/call-openfaas-serverless-functions-with-gloo-api-gateway-678a00710481 to community file
N/A
=> Add OF with Gloo API blog

community.md
=> Add self-hosting serverless with OpenFaaS to community.md

community.md
Signed-off-by: Christopher De Vries <devries@idolstarastronomer.com>
Added a link to the article I posted on my blog here: https://unnecessary.tech/posts/openfaas-cobol/ . 
This change keeps the list of blog posts up to date.
I ran this through my markdown parser in github mode and it looked to be formatted well.
=> Adding my blog article about creating a COBOL template

community.md
=> Add Docker and DevOps talk podcast to community

community.md
=> Add node12 and restify template blog to community.md

community.md
New blog from heyal.co.uk on openfaas `OpenFaaS, what's it all about?` 
Visually
=> Add a blog from heyal.co.uk

community.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
=> updated community.md with new article

ADOPTERS.md
Prior to this change, PiperCI was not a listed adopter. This change adds PiperCI to the list of adopters and provides a brief description.
Signed-off-by: codrcodz <cody.l.cochran@gmail.com>
Prior to this change, PiperCI was not a listed adopter. This change adds PiperCI to the list of adopters and provides a brief description.
Viewed rendered markdown in my fork to verify the appropriate placement in ADOPTERS.md
=> Add PiperCI

.github/ISSUE_TEMPLATE.md, docker-compose.arm64.yml, docker-compose.armhf.yml, docker-compose.yml
Update images including multi-arch
#1537
If you need to use arm64 - please do use Kubernetes, armhf and arm64 are not well supported on Swarm and outside of commercial engagement, we don't have the resources to give too much time over to supporting and debugging arm architecture with Swarm.
=> Update images including multi-arch

community.md
=> Updating blog post about Micronaut and OpenFaas

ADOPTERS.md
Added DB2 Limited to ADOPTERS.md file.
=> Added DB2 Limited to ADOPTERS.md

community.md
=> Add cisco blog to community.md

ADOPTERS.md
=> Added Cognite to ADOPTERS.md

community.md
Signed-off-by: Andreas Mosti <andreas.mosti@gmail.com>
=> Add NDC Oslo 2020 lightning talk to community.md

docs/README.md
Fix a link and tidy up and old pr (by fixing link)
closes #1455
clicked the link in the markdown file.
=> Fix broken link to point at workshop

community.md
=> Update community.md with new blogs

community.md
Update interviews, podcasts and featured talks
Updates and re-orders sections.
=> Update interviews, podcasts and featured talks

community.md
Added link to presentation given during the Open Source Summit in July 2020 to the community file
- via [Twitter](https://twitter.com/alexellisuk/status/1321478309738352641) :) 
Not required as it is only a documentation change
=> Add OSS presentation by Burton to community file

README.md
Update the link to the deployment page
related: #1588 
Fix broken link in README file.
=> Update link to deployment page

ADOPTERS.md
I like using faasd at my chuch so I thought I'd add a note in the adopters file.
=> Add First Baptist Church Carrollton to ADOPTERS.md

gateway/assets/index.html, gateway/assets/script/bootstrap.js, gateway/metrics/add_metrics.go
Fixes https://github.com/openfaas/faas/issues/1413
Fixes https://github.com/openfaas/faas-netes/issues/707
This fixes the Gateway UI not updating the
invocation count automatically without a page reload.
Tested by deploying on a local cluster and making sure invocations go up
with and without namespace suffix
=> Fix Invocation count wrong for multiple namespace

.github/workflows/build.yml, .github/workflows/publish.yml
There was an instance of the git commit message not being passed
correctly to the build, thus returning nil on the faas-cli version
command.
Broken PR Build from @alexellis which had a . in commit message not being parsed correctly.
Tested on a failing commit by amending the commit (keeping message) and
getting CI to run green
=> Fix parsing github commit status to container

community.md
Hello @alexellis 
I've published the article I've mentioned with you. Did I add it correctly in the community file?
Cheers,
Peter
=> Adding blog article

ADOPTERS.md
Signed-off-by: Simon Emms <simon@simonemms.com>
Add new adopter
Details how HM Planning Inspectorate are using OpenFaaS
=> Add HM Planning Inspectorate to Adopters

community.md
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>
closes #1622
=> List Blog posts in community.md updated till January 2021

ADOPTERS.md
Added Waylay as one of the adopters of OpenFaas.
=> Add Waylay to ADOPTERS.md

community.md
blogs: add new posts for 2021
No was a request to update the page with posts about openfaas
=> blogs: add new posts for 2021

community.md
Signed-off-by: Johan Siebens <johan.siebens@gmail.com>
=> blogs: add new post for 2021

ADOPTERS.md
We are using OpenFaaS in our project and updated adopters list
=> adopters smashHit.eu added

community.md
Signed-off-by: Johan Siebens <johan.siebens@gmail.com>
=> blogs: add new post for 2022

community.md
Just a markdown file update adding a link to yet another post about OpenFaaS.
=> Add blog post on OpenFaaS from iximiuz.com

community.md
Signed-off-by: Simon Emms <simon@simonemms.com>
Add OpenFaaS blog post
Blog post on subject of creating a RESTful API with serverless functions.
Explained in post
=> Add my blog post

.DEREK.yml
Signed-off-by: Han Verstraete <welteki@pm.me>
Add welteki for Derek curation
=> Add welteki for Derek curation

community.md
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>
Add blog post on wasm functions using Sat
=> Add blog post on wasm functions using Sat

community.md
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>
Add blog post on running faasd on azure arm vm
- [] My code follows the code style of this project.
=> Add blog post on running faasd on azure arm vm

community.md
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>
Add blog post on event-driven edge
=> Add blog post on event-driven edge

ADOPTERS.md
Signed-off-by: Arne Diekmann <diekmann@neoskop.de>
Adds an adopter
Adds Neoskop as an adopter to ADOPTERS.md
=> Add ADOPTER

community.md
Community guide has been updated for 
https://midnightprogrammer.net/post/installing-openfaas-on-k3s-single-node/
https://www.youtube.com/watch?v=-8MrDWg6K6s
Closes #1783
Documentation change was done. So no test is required.
=> Added Blog Post and Videos

community.md
community guide has been updated for all the latest blogs and videos for openfaas.
Closes #1785 
update is done in `community.md`. No tests are needed
=> update community guide for latest blogs and post

community.md
Update community blogs for latest articles
Closes #1787
=> update community guide

gateway/scaling/ranges.go
=> chore: remove refs to deprecated io/ioutil
