openfaas/faas

- watchdog/main.go
Fix buffer dead-lock in Watchdog.
Payloads of > 64KB choked due to buffer blocking waiting for another Goroutine to read at the other end. 
Fixes issue #31 
Tested with 1.9MB JPG / PNG through watchdog and gateway.
> Fix buffer dead-lock in Watchdog

- gateway/handlers/proxy.go
- sample-functions/AlpineFunction/Dockerfile
- sample-functions/AlpineFunction/README.md
- sample-functions/ApiKeyProtected/Dockerfile
- sample-functions/WebhookStash/Dockerfile
- watchdog/README.md
- watchdog/build.sh
- watchdog/config_test.go
- watchdog/main.go
- watchdog/readconfig.go
DNS-rr flag and Watchdog healthcheck
Gateway - enable DNS-RR as lookup option instead of VIP for high-load performance testing.
Watchdog - enable lock file for use with healthcheck in binary
DNS rr flag tested with `docker service logs func_gateway` after scaling function.
Healthcheck tested with sample function. Need to bake-in a timeout into each function or base image.
Could do with automated DIND tests for this scenario.
> DNS-rr flag and Watchdog healthcheck

- docker-compose.yml
- gateway/handlers/alerthandler.go
- watchdog/README.md
Provide override for replica scaling to cap out at custom value.
* A function can have a max override of 1 - i.e. it should not scale.
* A function should be able to scale beyond the hard-coded limit of 20 replicas.
A new label for container spec allows this:
```
com.faas.max_replicas: "10"
```
Existing functions unaffected. Tested with sample compose stack. After reaching max_replicas limit, the scaling will stop increasing replicas.
> Provide override for replica scaling to cap out at custom value.

- watchdog/README.md
- watchdog/config_test.go
- watchdog/main.go
- watchdog/readconfig.go
Allow override of contentType response from watchdog for when it does not match caller contentType. I.e. JSON request and binary output.
Fixes #45 
```
$ content_type=text/plain marshal_request=true fprocess=/bin/cat ./watchdog 
```
Shows response contentType set to text/plain.
```
$ marshal_request=true fprocess=/bin/cat ./watchdog 
```
Shows existing behavior of response contentType being matched.
> Allow override of contentType response from watchdog.

- watchdog/main.go
- watchdog/requesthandler_test.go
Measure watchdog function `exec` duration at execution point
Provides mechanism to measure actual execution time of binary in `fprocess` variable.
`X-Duration-Seconds` will be returned in the HTTP Header.
```
./faas-cli -action=deploy -image=tester -name=tired -fprocess="sleep 1"
```
```
alexr:faas-cli alex$ curl localhost:8080/function/tired -d "test" -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /function/tired HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: application/x-www-form-urlencoded
< Date: Wed, 03 May 2017 07:57:43 GMT
< …
```
> Add X-Duration-Seconds measurement for all functions via watchdog

- gateway/Dockerfile.multistage
- gateway/handlers/functionshandler.go
- gateway/metrics/swarmwatcher.go
- gateway/requests/requests.go
- gateway/server.go
Move UI to /ui/ URL-space and support env-vars for functions
* Having a specific URI for the UI will help with securing via a reverse proxy.
* Env-vars for functions allows for easy configuration
* Env-vars tested on Linux with Slack functions via faas-cli and YAML file.
* UI tested on Mac through Safari
> Move UI and support env-vars for functions

- community.md
The domain was missing from the link to http://jmkhael.io/serverless-and-on-my-own-servers/
Added jmkhael.io to http:///serverless-and-on-my-own-servers/ to make http://jmkhael.io/serverless-and-on-my-own-servers/
Correcting a typo
Browsed to the link
> Adding the domain to Johnny's serverless link

- community.md
This is adds the link to the slides.  They're not up yet in case there are last minute changes.
> add link to slide deck for GlueCon talk

- api-docs/swagger.yml
- docs/managing-images.md
- gateway/Dockerfile.build
- gateway/Dockerfile.build.armhf
- gateway/handlers/functionshandler.go
- gateway/requests/requests.go
- gateway/tests/registryauth_test.go
This adds support for private docker registries.
An optional `registryAuth` field in the CreateFunctionRequest
allows users to specify a registry auth to be used for deployment.
Auth must be passed as base64-encoded basic auth, similar to
how it's done in Docker file store credentials (~/.docker/config.json).
Credentials are then passed to swarm at service creation.
Support for private registries.
See issue #83 
Manual test procedure:
1) deploy a private registry with basic auth enabled (see https://gist.github.com/sebgl/3c97c379ddc77c65c44d47e6b745fa10)
2) push a docker image to the private registry
3) deploy a function with `"registryAuth": "base64user:password"`
Automated integration tests are a bit harder to perform due to the
need for a private registry with TLS + basic auth.
A few …
> Handle private docker registry auth

- community.md
Add link to FaaS Figlet blog post.
1. a light image is built from an Alpine base
2. uses Figlet tool internally
3. demo how to use faas-cli to deploy it.
So that we have a FaaS function generate Ascii banners.
> Add link to FaaS Figlet sample

- watchdog/README.md
- watchdog/config_test.go
- watchdog/main.go
- watchdog/readconfig.go
- watchdog/requesthandler_test.go
Watchdog refurbishments
- Watchdog - allow new methods with and without body.
- Enforce hard-timeout via exec_timeout variable - gives *408 Request Timeout*
- Correct bug in timeouts for read/write of HTTP. via @stealthybox #98
- Documentation for new verbs and hard timeout.
- cgi_headers now defaults to true for functions.
- Gateway unaffected by commits
- Tested through new and existing unit tests
- Tested through watchdog binary outside of container:
```
exec_timeout=2 fprocess="node test.js" ./watchdog
```
test.js:
```
function t() {
console.log("Stop");
}
console.log("Start");
setTimeout(t, 4000);
```
Result:
```
$ curl localhost:8080 -v
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost …
```
> Watchdog refurbishments

- gateway/Dockerfile.build
- gateway/Dockerfile.build.armhf
- gateway/Dockerfile.multistage
- gateway/Dockerfile.newbuild
- gateway/config_test.go
- gateway/readconfig.go
- gateway/server.go
- gateway/tests/config_test.go
New feature for Gateway Configuration Options
- Adds GatewayConfig
- Env configurable `read_timeout` & `write_timeout` /w test copied over from watchdog.
- Moves httpPort definition to the config default declaration.
- Modifies Dockerfiles to add new files and test code.
- Adds runtime logging for options.
Resolves #95 and #94 
Unit test and config were included in the `main` package instead of the `tests` folder because of access to unexported struct members.
The additional test gates the build.
This follows the same format as the watchdog.
I tested e2e functionality by setting the `read_timeout` and `write_timeout` ENV vars on the gateway container, checking the new log output, and following the steps in #94.
> Gateway Configuration with Timeouts

- docker-compose.armhf.yml
- gateway/Dockerfile.multistage.armhf
Ported multi-stage build and bumped gateway to 0.6.0 for armhf. 
armhf fell behind x86_64 in freshness
On a single RPi 3.
> Bump armhf Gateway to 0.6.0

- README.md
- deploy_stack.armhf.sh
- deploy_stack.ps1
- deploy_stack.sh
- Adds a one-liner `deploy_stack.ps1` PowerShell script in order to start the FaaS Docker stack on Windows.
- Updates README.md to call out scripts explicitly
When standing up the environment on Windows I defaulted to trying `docker-compose up`, only realising something was wrong when I read the warnings about `Compose does not support 'deploy' configuration`.
It also brings the user experience on Windows into line with Linux/OSX.
Have run locally on Windows 10 Pro (`10.0.15063 Build 15063`), tested the following scenarios:
- Docker not installed, returns a message pointing the user towards installing Docker.
- Swarm not initialised, the docker stack command returns a clear warning telling the user to swarm init.
- Successful deploy on a …
> Add one-liner ps1 script to start Docker stack on Windows

- gateway/assets/index.html
- gateway/assets/style/bootstrap.css
- Use monospace font inside code blocks
- Merge all fonts imports into one import (performances improvement)
The FaaS UI can be used to invoke functions on the cluster - it has two textboxes for request/response - both are using the default Angular material theme's font.
This requires a change in documentation, explaining that `monospace` class on an html tag will trigger code block display. 
Linked to #135 (and clone of closed #138)
This has been tested by @alexellis and works as expected
> Use Roboto Mono for code blocks & use on imports for all fonts

- gateway/metrics/externalwatcher.go
- gateway/server.go
Add gateway_service_count metric to Prometheus for external service provider (i.e. Kubernetes)
This will populate the gateway_service_count metric every 5 seconds for Kubernetes. It includes the replicas of a service and is normally 1 but may change with auto-scaling.
Tested on kubeadm cluster by typing `gateway_service_count` into Prometheus and watching the value change.
> Add gateway_service_count metric for external provider

- watchdog/Dockerfile
Quick and harmless ldflags change reduces binary size to about half for Watchdog
#163 
Within a container using AlpineFunction sample image
> Strip binaries to half of size

- gateway/handlers/reader.go
- watchdog/requesthandler_test.go
Signed-off-by: wgliang <liangcszzu@163.com>
should use strings.Contains() instead of stings.Index()
NONE
> should use strings.Contains() instead of stings.Index()

- CONTRIBUTING.md
Adds a line to CONTRIBUTING.md to mandate use of GH closure keywords in PRs and/or commits
Adds a line to CONTRIBUTING.md to mandate use of GH closure keywords in PRs and/or commits
Fixes #191
Enables automatic facility inherently available within GitHub to help project maintainers manage issues.  Upon merging of the PR associated & referenced issues will also be closed.
> Add line to mandate use of GH closure keywords - fixes #191

- gateway/handlers/createhandler.go
Return error when ServiceCreate fails in gateway/handler/createhandler.go
Signed-off-by: Eric Stoekl <ems5311@gmail.com>
Related issue: #195
> Return HTTP error response on 'MakeNewFunctionHandler' error

- gateway/handlers/createhandler.go
- gateway/tests/integration/createfunction_test.go
Signed-off-by: Alex Young <alex@heuris.io>
With an OpenFaas swarm stack running, run the gateway integration tests by doing the following from the root directory:
```
cd gateway/tests
go test ./integration
```
You should see all integration tests pass. Two were currently failing one due to the change done in #196 and another to do with an `X-Function` related issue that has been fixed in d2b15241c66a797cfacf903da6f24e5991893ff9.
> Add tests around error handing done in #196

- community.md
Signed-off-by: Johnny Mkhael <johnny.mkhael@gmail.com>
Adding a link to the community page concerning the last blog post I did.
Basically I created an OpenFaaS based stack to keep pinging my blog and then send a Slack notification in case the blog is down,
How Has This Been Tested?
NA
Checklist:
[x] I've read the CONTRIBUTION guide
[x] I have signed-off my commits with git commit -s
> Added link to DownNotifier post

- api-docs/swagger.yml
- gateway/handlers/createhandler.go
- gateway/handlers/update_handler.go
- gateway/server.go
This PR is part of a group of 3:
- openfaas/faas#208
- openfaas/faas-cli#123
- openfaas/faas-provider#4
This PR implements an update handler for Docker Swarm, it queries the current spec, updates values in-situ before calling ServiceUpdate.
It also switches to using the PUT verb for updates.
Testing with the following setup:
- Single Docker instance running an insecure registry
- 3 Node Swarm deployed  with `--engine-insecure-registry` for the registry above.
See this [gist](https://gist.github.com/johnmccabe/55baab605c0fb82df9c1cbf8c3dde407) for details on how this was setup (on Windows 10).
Tested using an updated `ruby-echo` function, with the following function yaml.
```
provider:
name: faas
gateway: http://10.10.10.198:8080
network: "func_functions"
ruby-echo:
lang: ruby
handler: …
```
> Implement Swarm update handler (and use PUT method for updates)

- gateway/assets/img/icons/ic_arrow_back_white.svg
- gateway/assets/img/icons/ic_menu_white.svg
- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
The current gateway UI's `sidenav` hides when the screen's width is below 960px. I've added a toggle menu button when the screen's width is below 960px. Now you can toggle the `sidenav` even though the screen is small. The function is as below.
The issue is mention at #180 .
I've tested this by deploying it on a Rancher backed OpenFaaS environment and opening up the gateway UI. Shrinking and stretching it to see if the toggle menu works correctly.
> Sidenav toggle button

- watchdog/main.go
This PR fixes issue #245 of the lock file not being crossplatform because of just using '/tmp/'. os.TempDir() is used to find a temporary dir, completely crossplatform. ~~Because of this, suppressLock is no longer needed and has been removed.~~
I built the code, ~~removed the tests for supressLock and the parts of suppressLock in the config since it's not needed,~~ also tested the `filepath.Join(os.TempDir(), ".lock")` code on a Windows and Linux computer, and the actual fwatchdog file on Windows and Linux.
I'm fairly new to collaborating and commiting to projects so please LMK if I did anything wrong. I don't believe new tests are needed as well but am unsure, as well as with docs.
> Fixes #245 Added os.TempDir() to replace using '/tmp/'

- community.md
Adds a section to call out industry mentions as distinct from community.
Adds the Bossie Award and RedPoint FaaS landscape.
Differentiate industry mentions from community.
n/a
> Add Industry awards and mentions section

- .travis.yml
Added push to Docker Hub on git tag with image tagging
Must set the Travis-CI environment variables on the project:
DOCKER_USERNAME and DOCKER_PASSWORD
in order to log in to docker for the push. Make sure the setting 'Display value in build log' is disabled
This will run when a git tag is pushed into the repository. It will push one image with the git tag value
Hacktoberfest!
`git tag -a 1.0 -m "Tagging the commit"`
`git push origin 1.0`
then watch Travis do the work!
> Fixes #235 - Add docker push to travis.yml

- gateway/handlers/proxy.go
- gateway/requests/forward_request.go
- gateway/tests/forward_request_test.go
- watchdog/main.go
Forward path and query string all the way through proxy to the watchdog and forked process
Brings work forward out of WIP PR:
#174 
A good way to test is to build a new watchdog and gateway, then deploy functions/alpine with the fprocess as `env` - then try adding different query URLs or query strings along with the proxy request.
> Forward path and query string through proxy

- community.md
ucalgary/ftrigger provides label-based triggers for OpenFaaS functions.
There is currently a working implementation for Kafka topic messages.
> Add ftrigger as a community project

- TestDrive.md
- guide/chaining_functions.md
- guide/deployment_k8s.md
Remove '--name' in faas-cli invoke
Doc can not execute. '--name' is removed.
see:https://github.com/openfaas/faas-cli/commit/e0973014146164fbefae3bbd34d644e921b2ae98#diff-6e522d40e6848a6eeeb12b0ab50cb97d
> Remove '--name' in faas-cli invoke

- docker-compose.yml
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>
We would like the network running on Docker Swarm attachable.
Actually `docker-compose.yml` v3.3 is supported by Docker 17.06.2+.
This fix is trivial.
0. `./deploy_stack.sh` it should deploy the stack without error.
0. `docker inspect func_functions` it should show that this network is attachable.
This change allows use to attach other services to the current stack.
This change will make 17.06.2 the minimum version of Docker required by OpenFaaS.
> change to use 3.3 spec to allow attachable network

- api-docs/swagger.yml
The optional body parameter to be passed to STDIN wasn't part of the previous swagger spec.
The title really says it all. I loaded the http://editor.swagger.io/ editor and couldn't see the body parameter, so I've added it as an optional parameter. It looks like the editor re-organised the response codes to numeric order, so I've left the changes in, in-case anyone else wants to verify or generate code using http://editor.swagger.io/
This is more like documentation than code, but follows https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md and http://editor.swagger.io/
> Added optional body to function calls

- watchdog/README.md
- watchdog/config_test.go
- watchdog/main.go
- watchdog/readconfig.go
Made write_debug false by default. Added log message to show amount of bytes written (to show it worked)
Fixes https://github.com/openfaas/faas/issues/251
Ran the markdown function with several lines of text (as described in the ticket). Verified the output was unchanged, but the logs now only show "Wrote 48 Bytes". Before, the logs would have every line of the output.
> 251 debug write default false

- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
- Add a simple sinner when the function is invoked
- Disable the invoke button until the request returns
This change provides better user experience and feedback while waiting for function invocation to finish.  This specifically address #328 
Tested manually in the browser, see the gif attached below
> Add spinner during function invoke in the web ui

- gateway/handlers/reader.go
- gateway/tests/reader_test.go
Signed-off-by: Alex Young <alex@heuris.io>
This is the beginning of the work on creating a more RESTful API (#214). It can be considered for merging on it's own however if there is work already happening to address this issue.
- If the call to ServiceList fails in the reader, 500 is returned with an error message. Before this change the handler returned 200 with the string `null`.
- If there are no functions then an empty array is returned. Before this change, the string `null` was returned
Running unit tests in `reader_test.go`.
> [WIP] Return 500 if GET /system/functions fails

- contrib/nginx/.gitignore
- contrib/nginx/Dockerfile
- contrib/nginx/README.md
- contrib/nginx/gateway.conf
Minimal example for validation / testing to setup basic auth with Nginx for the whole gateway.
Context - #349
This requires some manual steps which means it won't be possible to do a `docker stack deploy` and get going. Here's the workflow:
* Create .htpassword using CLI
* Create Docker secret using CLI
* Deploy stack
The main change is that the gateway would not be exposed, but Nginx would be instead.
> Suggestion - basic auth security with Nginx

- gateway/metrics/add_metrics.go
- gateway/metrics/prometheus_query.go
- gateway/server.go
- gateway/tests/add_metrics_test.go
Set content-type for mixed-in Prometheus results
Metrics are sometimes sent back as text/plain, this corrects the Content-Length and begins unit test coverage.
Suggestion by @nullseed 
Unit tested and full build
> Set content-type for mixed-in Prometheus results

- watchdog/README.md
- watchdog/main.go
- watchdog/requesthandler_test.go
Add Http_ContentLength for deterministic functions
Enables deterministic reading from stdin. cc/ @Lewiscowles1986 
With unit tests and the `env` built-in shell command.
Set process to `env` and pass a body of `test`
```
...
Http_ContentLength=4
...
```
See README.md for updates
> Add Http_ContentLength for deterministic functions

- gateway/handlers/createhandler.go
- gateway/handlers/reader.go
- gateway/handlers/update_handler.go
- gateway/requests/requests.go
- gateway/tests/reader_test.go
New feature - Return labels through function reader
We can current input / set labels, but this allows the metadata to be consumed by other clients such as a gateway-connector by reading /system/functions.
Tested by adding new labels to samples.yml in the faas-cli.
Related: https://github.com/openfaas/faas-netes/pull/75
> Return labels in functions list endpoint

- gateway/handlers/proxy.go
- watchdog/Makefile
- watchdog/main.go
Enable GET method for functions. This is work in-progress and may need review - i.e. to allow functions to opt out of this method whether it causes them to block or wait for input.
Todo:
User request for "GET" support. Also asked for by @JockDaRock for Flask/Express support.
Tested in a web-browser and on the command-line, also benefits from fixes in #318
Additional testing and tyre-kicking appreciated.
> [WIP] Enable GET method for functions

- gateway/assets/script/bootstrap.js
Signed-off-by: Javier Revillas <jrevillas@massivedynamic.io>
This will render JSON responses from functions in accordance with #398.
Enables the possibility to fire functions that consume plain text and return JSON. Fixes issue #398.
This code has been tested following instructions from `contrib/HACK.md` and using the `SentimentAnalysis` function as a reference.
> Fix JSON serialization relying on response content

- DEV.md
- docker-compose.arm64.yml
- docker-compose.armhf.yml
- docker-compose.extended.armhf.yml
- docker-compose.extended.yml
- docker-compose.yml
Removes depends_on tag from docker-compose.yml files and documentation
Fixes #198, and updated `DEV.md` documentation accordingly.
Executing `docker stack --compose-file=docker-compose.yml deploy` for all the changed files and verifying all the services were up and runnin.
> Removes depends_on tag from docker-compose.yml files and documentation

- TestDrive.md
- gateway/handlers/alerthandler.go
- gateway/handlers/cors.go
- gateway/handlers/create_handler.go
- gateway/handlers/forwarding_proxy.go
- gateway/handlers/proxy.go
- gateway/handlers/queueproxy.go
- gateway/handlers/reader.go
- gateway/handlers/update_handler.go
- gateway/metrics/prometheus_query.go
- gateway/metrics/swarmwatcher.go
- gateway/plugin/external.go
- gateway/server.go
- gateway/tests/alerthandler_test.go
- gateway/tests/cors_test.go
- gateway/tests/proxy_test.go
- gateway/tests/reader_test.go
- gateway/tests/registryauth_test.go
- gateway/tests/resources_test.go
- gateway/tests/unmarshall_test.go
- gateway/types/handler_set.go
- gateway/types/http_adapter.go
Feature: Add min/max scale for auto-scaling - Swarm & external providers 
See: #414 
With new tests and with Stefan via gateway and kubernetes
> Feature: Add min/max scale for auto-scaling - Swarm & external providers 

- guide/deployment_k8s.md
Small k8s faas-netes installation docs fix, namespace.yml is at the root of the project.
> fix k8s fass-netes deploy docs, namespace.yml is at the root of the repo.

- contrib/HACK.md
This updates the documentation needed to manually spin up a container for the gateway. The updated command will mount the gateway into the unprivileged user's home directory. This will also set a new environment variable: `functions_provider_url`.
This command has been tested on a local environment with MacOS High Sierra 10.13.3 and Docker CE 18.02.0-ce-rc2-mac51 (22446).
> Update HACK.md in accordance with #454

- guide/deployment_swarm.md
- guide/deployment_swarm_arm.md
Simple change to the swarm guides to accommodate Compose 3.3.  Fixes #499
see #499 
- [ x ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
17.06 is detailed by docker as supporting compose 3.3.
> Moved supported Docker version to 17.06 to enable 3.3 of compose

- gateway/assets/script/bootstrap.js
Signed-off-by: Ken Fukuyama <fukuyama@supersoftware.co.jp>
Because the ajax requests used the paths from the root, the gateway UI didn't work correctly via `kube proxy`. Using relative paths for the requests would solve this problem.
This is the [same fix](https://github.com/containous/traefik/pull/492) traefik has made, too.
People who use the gateway via `kube proxy` cannot use the UI currently.
This fixes issue #519.
I've spun up a kubernetes cluster with docker on mac. Deployed openfaas and checked
* Create
* Delete
* Invoke (downloaded an image, too)
both with and without `kube proxy`.
> Fixed UI to use relative paths for ajax requests in order to work with `kube proxy`

- watchdog/config_test.go
- watchdog/readconfig.go
added go duration support for read_timeout, write_timeout, exec_timeout in watchdog
> added go duration support for timeout config in watchdog

- gateway/requests/requests.go
Add AvailableReplicas field to `requests.Function` struct. 
Without this field (or equivalent), it's impossible to tell if the function is ready to serve incoming invocations. 
Looks like openfaas/faas-netes#67 is blocked until this change is in. 
```
$ go test ./gateway/{tests,requests}
```
> Add AvailableReplicas field to requests.Function

- api-docs/swagger.yml
- docker-compose.yml
- gateway/server.go
Expose function endpoint from underlying provider
This means a new route: `/system/function/{name:[-a-zA-Z_0-9]+}`
Required to expose underlying function information for a single function.
Todo:
Tested with the Swarm provider:
```
$ curl 127.0.0.1:8080/system/function/func_base64 | jq
{
"name": "func_base64",
"image": "functions/alpine:latest@sha256:4145602d726a93ed2b393159bb834342a60dcef775729db14bef631c2e90606f",
"invocationCount": 0,
"replicas": 1,
"envProcess": "base64",
"labels": {
"com.docker.stack.image": "functions/alpine:latest",
"com.docker.stack.namespace": "func"
}
}
```
When function not found:
```
$ curl 127.0.0.1:8080/system/function/doesnt_exist -i
HTTP/1.1 404 Not Found
Content-Length: 0
Content-Type: text/plain; …
```
> Expose function endpoint from underlying provider

- sample-functions/build_all.sh
Updated the build script (*sample-functions/build_all.sh*) for the sample functions to reference *stack.yml* 
1. I ran the build script, which resulted in this error:
```sh
$ cd sample-functions && sh build_all.sh
Open samples.yml: no such file or directory
```
Yikes!
2. I hypothesized that *samples.yml* had been renamed to *stack.yml*. After a thorough investigation, I came across [this](https://github.com/openfaas/faas/commit/bf91f3f0a77200b79947c1569acef7f2db697b85#diff-ab3375c51a9e6d2be1985cf8a17ed9f4) commit, which confirmed my hypothesis.
Yes, I tested it locally.
> updated build script

- docker-compose.yml
- gateway/handlers/alerthandler.go
- gateway/handlers/forwarding_proxy.go
- gateway/handlers/service_query.go
- gateway/plugin/external.go
- gateway/server.go
- gateway/types/proxy_client.go
- gateway/types/readconfig.go
Use Go context to enforce upstream timeouts
The upstream recently changed to use a http.Client in #552 - if the read/write timeout duration is exceeded then the client receives and empty response. This is as-designed in the Go stdlib but not all browsers understand how to handle that. This WIP change allows for a header to be sent back if the upstream call exceeds its timeout.
I also plan to introduce a new environmental variable `upstream_timeout` which would represent the maximum time for running a function in the back-end provider.
Docker Swarm + faas-swarm, Kubernetes + faas-netes 2.0
> Use Go context to enforce upstream timeouts

- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
Fixes #555 
Tested with faas-netes which provides `availableReplicas` on the `/system/function/<name>` endpoint.
This change requires a change to faas-swarm and faas-nomad to report `availableReplicas` = 1 all the time, or optionally when the underlying container is ready.
Update the gateway to the `functions/gateway:pr554` for testing
Breaking change to UI only, not to the API.
> Make UI block "Invoke" button until function reports readiness

- watchdog/main.go
- watchdog/requesthandler_test.go
Introduces new endpoint `/health` in watchdog.
This change covers the first part of this issue https://github.com/openfaas/faas/issues/547
It has been tested on a local system (Mac) by building the watchdog and doing curl for the `/health` endpoint.
> Watchdog endpoints for health

- watchdog/Dockerfile
- watchdog/readconfig.go
- watchdog/readconfig_test.go
The default should be set to true so we maintain backwards.
compatibility. readconfig.go was altered due to bug reading default value. 
Issue spotted by Ivana @iyovcheva 
This was tested by adding unit tests to readconfig_test.go for positive and
negative scenarios.
Also built a local watchdog and checked default behavior was fixed.
> Fix bug reading default value for combine_output

- gateway/handlers/cors.go
- gateway/server.go
- gateway/tests/cors_test.go
- watchdog/main.go
- watchdog/requesthandler_test.go
This commit replaces occurences of http method strings with the corresponding consts from the http package.
*Note* `UPDATE` is not strictly speaking a valid method and as such isn't part of the http package so these occurrences have not been altered (should be a `PUT` or `PATCH`?)
Motivation is to avoid the use of magic strings in code.
Verified that existing test suite results are identical to those prior to the change.
> Refactoring suggestion: Use http package consts for http methods

- gateway/assets/index.html
This will replace the gateway URL showing up as the title.
Signed-off-by: David Muckle <dvdmuckle@dvdmuckle.xyz>
Added a <title> element to the index.html of gateway to display "OpenFaaS Portal" as the title for the UI.
Built and run on my own cluster.
> Add a title to the index.html for the gateway

- guide/deployment_digitalocean.md
Signed-off-by: Marko Mudrinić <mudrinic.mare@gmail.com>
This PR updated DigitalOcean Deployment guide to use Ubuntu 17.10 instead of 17.04.
17.04 is not available anymore on DigitalOcean, so `docker-machine` returns the following error:
```
Creating machine...
(node-1) Creating SSH key...
(node-1) Creating Digital Ocean droplet...
Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.
```
> guide,do: switch to ubuntu-17-10-x64

- watchdog/main.go
- watchdog/requesthandler_test.go
Add feature for graceful shutdown of HTTP server
If the watchdog is sent SIGTERM from an external process then it
should stop accepting new connections and attempt to finish the
work in progress. This change makes use of the new ability in Go
1.9 and onwards to cancel a HTTP server gracefully.
The write_timeout duration is used as a grace period to allow all
in-flight requests to complete. The pattern is taken directly from
the offical example in the Golang documentation. [1]
Further tuning and testing may be needed for Windows containers which
have a different set of signals for closing work. This change aims
to cover the majority use-case for Linux containers.
The HTTP health-check is also invalidated by creating an and
expression with the existing lock file.
Tested with Kubernetes by …
> Add feature for graceful shutdown of HTTP server

- .travis.yml
- contrib/ci.sh
- gateway/Dockerfile
- gateway/server.go
- gateway/tests/integration/routes_test.go
- watchdog/Dockerfile
Get is a supported method so this test failed, I've now changed
this to an unsupported method - i.e. HEAD to trigger the error
and keep the test.
Deprecates routeless proxy and related test. 
Changes to the tests also ensure that the built version of the gateway is deployed
for testing rather than the latest release.
Integration tests and the certifier have not been running correctly for some time. This enables them to run.
Via Travis CI
> CI: update Travis to use Go 1.9 for integration tests

- gateway/assets/script/bootstrap.js
Fixed the UI so that when an error occurs, the tab automatically changes
to the manual tab in order to show the errors.
When an error occurs on the function store deployment, the tab will switch to the Manual Deploy tab. Hence, showing what error occurred.
Issue #481 
1. Deploy a function from store
2. Try to deploy the same function from store
3. Confirm that the tab switches to the manual deploy tab and shows the error.
Tested Browsers:
* Chrome
* Safari
* Firefox
* IE11
* Edge
Regression Tests:
* Deploy, Invoke, Delete a function
* figlet
* qr-code
> On funcstore error, change to manual tab

- gateway/handlers/alerthandler.go
- gateway/handlers/alerthandler_test.go
- gateway/handlers/service_query.go
- gateway/plugin/external.go
- gateway/plugin/external_test.go
Implemented the proportional autoscaling steps based on the maxReplicas as described in #569. Additionally, I added support for a label `com.openfaas.scale.factor` which allows configuring the proportion, setting it to 0 even allows to disable autoscaling. 
Signed-off-by: Simon Pelczer <templum.dev@gmail.com>
I updated the signature for `CalculateReplicas` to also take in `scalingFactor uint64` which will be used to calculate the scaling step. This value can be set using a label `com.openfaas.scale.factor`, which also can be used to disable auto-scaling (by setting it to zero). I updated the existing tests for `alerthandler.go` to reflect the done changes. Additionally, I created a dedicated test for the disable functionality when setting `scalingFactor = 0 `.
-  #569 
- Executed all of …
> [Merge] Implemented the autoscaling steps to be proportions of the max replicas.

- sample-functions/apikey-secret/README.md
Following the existing README instructions would result in an error
when the user attempted to create the secret.  This small change
remediates the instruction so that the secret is successfully created.
The secret would previously fail to create.  This change corrects that.
Ran through the steps and confirmed as working
> Fix apikey-secret README.md

- docker-compose.armhf.yml
- docker-compose.yml
- gateway/README.md
- gateway/handlers/basic_auth.go
- gateway/handlers/basic_auth_test.go
- gateway/server.go
- gateway/types/load_credentials.go
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
Fixes https://github.com/openfaas/faas/issues/687 allowing the
gateway to handle the responsibility of basic auth for when it is
in use.
To enable set basic_auth env-var to true and then mount two
secrets or plaintext files under /var/secrets/
basic_auth_user, basic_auth_password
#687
Tested with faas-cli list/deploy and with Safari browser.
> Enable basic auth on gateway

- README.md
Add a link to the documentation source repo 
> docs: add link to documentation source repo

- README.md
Resolves #711 
This update removes the PWD button from the readme
Play-with-Docker was unreliable for automatic deployment causing
confusion with users attempting to get started quickly
Walked through the steps to verify they are valid for a PWD deployment.
> Remove PWD link in readme

- DEV.md
- gateway/Dockerfile
- gateway/Dockerfile.arm64
- gateway/Dockerfile.armhf
- sample-functions/ApiKeyProtected-Secrets/Dockerfile
- sample-functions/BaseFunctions/golang/Dockerfile
- sample-functions/BaseFunctions/golang/Dockerfile.win
- sample-functions/DockerHubStats/Dockerfile
- sample-functions/DockerHubStats/Dockerfile.armhf
- sample-functions/MarkdownRender/Dockerfile
- sample-functions/WebhookStash/Dockerfile
- watchdog/Dockerfile
Updates all the references to golang from 1.9.4 (and 1.9.2 in the case of the gateway arm64 image) to 1.9.7.  
Issue #660 has been open for a while and seemed like it would make a good first issue.
Basic tests using functions loaded from the function store including the nslookup, hubstats, and nodeinfo using my dev docker images in swarm on an x86_64 VM.  I also deployed the updated gateway to my raspberry pi kubernetes cluster and validated that the nodeinfo and nslookup worked.
> Update to golang 1.9.7

- docker-compose.armhf.yml
Updated the queue-worker version in the `docker-compose.armhf.yml` file
The remaining services in the `armhf` file were already at the latest versions
This came up in conversation with Alex on Slack
This was tested using faas-netes on a 4-node RPi cluster with no issues. I don't see any reason this would cause any issues on Swarm, however, I do not have an armhf Swarm cluster available
- [\X] My code follows the code style of this project.
> Update armhf queue-worker version

- gateway/handlers/forwarding_proxy.go
- gateway/handlers/forwarding_proxy_test.go
When determining the service name of the function, remove any trailing
slashes, the slashes are not allowed in service names for either Swarm
or K8S, so this can only be a left over from the url path
- This was preventing service resolution, and hence failed functions,
when the function was called with a trailing slash. See #714
I have added a unit test, I have not tested a deploy yet because it is getting late here, but I wanted to get something posted incase someone else was feeling like testing.
I did run my test prior to update the method, and they were failing with the trailing slash.  They now pass.
> [WIP] Trim tailing slash from service name before proxy

- guide/secure_secret_management.md
- sample-functions/ApiKeyProtected-Secrets/handler.go
- sample-functions/apikey-secret/handler.go
- Update the documentation about secret management to note the changed
file location
- Remove the documentation on secret rotation, because this will not
currently work
- Update apikey-secret and ApiKeyProtected-Secrets to read secret values
from both the old and the new locations
Recent updates to faas-swarm and faas-netes changed the mount location
of secrets to implement #692.  These changes update the docs to reflect this change.
> Update secret docs and sample-functions

- gateway/Gopkg.lock
- gateway/Gopkg.toml
- gateway/vendor/github.com/openfaas/nats-queue-worker/.travis.yml
- gateway/vendor/github.com/openfaas/nats-queue-worker/Gopkg.toml
- gateway/vendor/github.com/openfaas/nats-queue-worker/handler/handler.go
- gateway/vendor/github.com/openfaas/nats-queue-worker/handler/handler_test.go
Update nats queue worker package to support host names with periods `.`
Without this update you can not run OpenFaas gateway on AWS Fargate
I tested this using the integration pack `gateway/tests/integration`
```
=== RUN   TestCreate_ValidRequest
--- PASS: TestCreate_ValidRequest (0.03s)
=== RUN   TestCreate_InvalidImage
--- PASS: TestCreate_InvalidImage (0.00s)
=== RUN   TestCreate_InvalidNetwork
--- PASS: TestCreate_InvalidNetwork (0.00s)
=== RUN   TestCreate_InvalidJson
--- PASS: TestCreate_InvalidJson (0.00s)
=== RUN   TestDelete_EmptyFunctionGivenFails
--- PASS: TestDelete_EmptyFunctionGivenFails (0.00s)
=== RUN   TestDelete_NonExistingFunctionGives404
--- PASS: TestDelete_NonExistingFunctionGives404 (0.00s)
=== RUN   TestGet_Rejected
2018/06/21 20:59:44 Head …
```
> Update nats-queue-worker package to 0.4.7

- docker-compose.armhf.yml
- docker-compose.yml
- gateway/README.md
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
This changes updates the secret mount path default value to
/var/openfaas/secrets at serveral places. It has been changed
from /run/secrets/ to /var/openfaas/secrets after version 0.8.2
I have tested this on my local system.
> Updated default secret mount path value

- docker-compose.armhf.yml
- gateway/README.md
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
This commit reverts the changes done in #738 to update the default
secret mount path to `/run/secrets/`
> Update default secret mount path to /run/secrets/

- build.sh
- gateway/Dockerfile
- gateway/build.sh
- gateway/handlers/infohandler.go
- gateway/server.go
- gateway/tests/integration/infohandler_test.go
- gateway/tests/integration/routes_test.go
- gateway/types/inforequest.go
- gateway/version/version.go
- watchdog/build.sh
Extend the health endpoint and add gateway version information
To help debugging and operating the gateway i've included the gateway
version information in `/system/info`
This has been tested locally using the docker-compose file in root
Request: `curl http://localhost:8080/system/info -s | jq`
Response:
```json
{
"provider": {
"provider": "faas-swarm",
"version": {
"sha": "c890cba302d059de8edbef3f3de7fe15444b1ecf",
"release": "0.3.3"
},
"orchestration": "swarm"
},
"version": {
"commit_message": "extends info endpoint",
"sha": "e85888b6122af1f084cf565462572220cc09cf28",
"release": "dev"
}
}
```
I've also ran the integration tests:
```bash
=== RUN   TestCreate_ValidRequest
--- PASS: TestCreate_ValidRequest (0.04s)
=== RUN   TestCreate_InvalidImage
--- PASS: TestCreate_InvalidImage (0.01s) …
```
> Enhance info endpoint to include gateway version

- .travis.yml
With this change gateway will be pushed to Quay.io on release
as a backup
[#741](https://github.com/openfaas/faas/issues/741)
Not tested yet. Requires setting environmental variables to Travis.
> Push gateway image to both Quay.io and Docker Hub

- CONTRIBUTING.md
- gateway/Dockerfile
- Core contributors are added by name.
- Copyright notice now encourages OpenFaaS Author(s) in place of
OpenFaaS Project to reflect the nature of distributed copyright.
> Add core contributors / copyright header update

- watchdog/build.sh
This moves watchdog to a better name for images and also gives free
image-scanning and gives more confidence  to users  that components
ship regularly and makes any vulnerabilities  in  components  clear
[#741](https://github.com/openfaas/faas/issues/741)
Tested with local build
> Move watchdog from functions/ to openfaas/ ns

- docker-compose.yml
After editing queue-worker to push do openfaas/ ns instead of
functions/ this chage is required to match the image name
Requires [#31](https://github.com/openfaas/nats-queue-worker/pull/31) to be merged in first
[#741](https://github.com/openfaas/faas/issues/741)
Not tested yet. Requires setting environmental variables to Travis.
> Edit queue-worker image with openfaas ns

- deploy_stack.sh
- docker-compose.yml
This changes uses environment variable to enable and disable basic_auth
configuration in `docker-compose.yml'. It also has default value 'true`
for basic_auth.
I have tested on my local (Docker for mac)
> Use env-var for basic_auth value for auto-auth script

- deploy_stack.sh
- docker-compose.yml
Enable basic-auth by default.
This changes ./deploy_stack.sh to generate and then apply secrets turning
on the built-in basic auth feature of the gateway.
#350 #74 
The deployment script will enable basic-auth by default to help
avoid people deploying to a public IP with no protection from
malicious actors.
Tested on MacOS with and without --no-auth flag.
Does not apply for armhf or powershell.
Example workflow for testing:
Test with positive and negative workflows: positive - password supplied and consumed, show that auth is working by using wrong password. Negative flow - disable auth and check auth is not required.
Will need documentation change and change to integration tests to disable auth via `--no-auth` flag when deploying during testing.
> Enable basic-auth by default

- gateway/Dockerfile
- gateway/README.md
- gateway/handlers/function_cache.go
- gateway/handlers/function_cache_test.go
- gateway/handlers/scaling.go
- gateway/server.go
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
This change allows functions to be "idled" or scaled to zero
replicas and then be invoked later on. There is a penalty to
scaling up - the API gateway proxy will block until the function
is ready.
A cache is included to off-set the calls to upstream API to check
on readiness along with unit tests.
Addresses part of #238 
Testing via scaling to zero replicas and then invoking function.
On Swarm I observed 3 seconds on an Intel Nuc i5 for scaling back
from zero replicas.
> Add feature: scale from zero to 1 replicas

- .gitignore
- .travis.yml
- Makefile
- api-docs/swagger.yml
- contrib/ci.sh
- gateway/requests/requests.go
- gateway/tests/integration/README.md
- gateway/tests/integration/infohandler_test.go
- sample-functions/WebhookStash/handler.go
Annotation attributes are metadata for functions which may be used by
the back-end for making scheduling or routing decisions.
I ran the `contrib/ci.sh` script:
```
Running integration tests
=== RUN   TestCreate_ValidRequest
--- PASS: TestCreate_ValidRequest (0.02s)
=== RUN   TestCreate_InvalidImage
--- PASS: TestCreate_InvalidImage (0.00s)
=== RUN   TestCreate_InvalidNetwork
--- PASS: TestCreate_InvalidNetwork (0.00s)
=== RUN   TestCreate_InvalidJson
--- PASS: TestCreate_InvalidJson (0.00s)
=== RUN   TestDelete_EmptyFunctionGivenFails
--- PASS: TestDelete_EmptyFunctionGivenFails (0.00s)
=== RUN   TestDelete_NonExistingFunctionGives404
--- PASS: TestDelete_NonExistingFunctionGives404 (0.00s)
=== RUN   Test_InfoEndpoint_Returns_200
--- PASS: Test_InfoEndpoint_Returns_200 (0.00s)
=== RUN …
```
> Adds annotation attribute to CreateFunctionRequest

- docker-compose.yml
This commit bumps gateway version to 0.8.7 in docker-compose.yml and
also adds `scale_from_zero` environment variable to the gateway.
Fixes: #780
> Bump gateway version to 0.8.7

- .DEREK.yml
As suggested by @alexellis in https://github.com/openfaas/faas-cli/issues/436#issuecomment-409965422 i've added my github handle to the maintainers array in `DEREK.yml`
> Add ewilde to .DEREK.yml maintainers list

- docker-compose.yml
This updates faas-swarm version including a fix for annotations.
In version 0.4.0 the prefix was not removed from the annotation
key, which was causing errors trying to get the value
Tested with [kafka-connector/pull/6](https://github.com/openfaas-incubator/kafka-connector/pull/6)
> Bump up faas-swarm to 0.4.1

- watchdog/handler.go
All verbs used with REST APIs are now supported: "GET", "POST", "PUT",
"PATCH", "DELETE"
Part of : openfaas/faas#815
To test the new verbs I created a custom `Dockerfile` template with the new version of watchdog and deployed `envtest`
Below is the output when invoking the function using the new http verbs
Note `Http_Method=PATCH` below
```
curl -X PATCH http://localhost:8080/function/env-test -i
HTTP/1.1 200 OK
Content-Length: 403
Content-Type: text/plain; charset=utf-8
Date: Sun, 19 Aug 2018 18:09:24 GMT
X-Call-Id: 0d6aee33-5a1d-4e30-8c37-602d4e340133
X-Duration-Seconds: 0.001461
X-Start-Time: 1534702164598405665
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=9fcfbb9b0fd2
fprocess=env
HOME=/root
Http_User_Agent=curl/7.60.0
Http_Accept=*/* …
```
> Adds support for PATCH HTTP verb in watchdog

- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
This minor fix selects the 'Download' radio button by default if the function has a label with `com.openfaas.ui.ext`. This will improve the UX for people who use the function store.
#827 
**Function with `com.openfaas.ui.ext` label**
1. Deploy the QRCode function which has the `com.openfaas.ui.ext` label.
2. Select the function from the list.
3. Check that the `Download` button is selected by default.
**Function without `com.openfaas.ui.ext` label**
1. Deploy the Figlet function which doesn't have the `com.openfaas.ui.ext` label.
2. Select the function from the list.
3. Check that the `Text` button is selected by default (not the Download button).
Tested with:
* Chrome
* Safari
* Firefox
* Edge
* IE11
> Automatically select 'Download' for store functions

- community.md
This updates the blog post section with OpenFaaS being mentioned
on Cisco DevNet Sandbox Cloud section and blog post for OpenFaaS
on Kubernetes from 2 Jan 2018 again in DevNet Sandbox
Follows up #810
> Update blog post/write-ups section with Cisco DevNet Sandbox

- gateway/build.sh
- gateway/handlers/forwarding_proxy.go
- gateway/handlers/forwarding_proxy_test.go
- gateway/handlers/function_prefix_trimming_url_path_transformer_test.go
- gateway/handlers/queueproxy.go
- gateway/handlers/transparent_url_path_transformer_test.go
- gateway/queue/types.go
- gateway/server.go
- gateway/types/readconfig.go
Closes #789
Docker image for testing: `alexellis/gateway:http-paths`
> Code review PR of #789 - HTTP paths for functions

- docker-compose.yml
Updated Swarm image versions for Prometheus &
Alertmanager to match Kubernetes stack
- Prometheus: v2.2.0 => v2.3.1
- Alertmanager: v0.15.0-rc.0 => v0.15.0
Signed-off-by: Patricio Diaz <padiazg@gmail.com>
> Bump Prometheus & AlertManager

- DEV.md
- sample-functions/AlpineFunction/Dockerfile
- sample-functions/AlpineFunction/Dockerfile.arm64
- sample-functions/AlpineFunction/Dockerfile.armhf
- sample-functions/BaseFunctions/R/Dockerfile
- sample-functions/BaseFunctions/cobol/Dockerfile
- sample-functions/BaseFunctions/coffee/Dockerfile
- sample-functions/BaseFunctions/dncore/Dockerfile
- sample-functions/BaseFunctions/golang/Dockerfile
- sample-functions/BaseFunctions/java/Dockerfile
- sample-functions/BaseFunctions/node/Dockerfile
- sample-functions/BaseFunctions/python/Dockerfile
- sample-functions/CaptainsIntent/Dockerfile
- sample-functions/ChangeColorIntent/Dockerfile
- sample-functions/HostnameIntent/Dockerfile
- sample-functions/NodeInfo/Dockerfile
- sample-functions/NodeInfo/Dockerfile.arm64
- sample-functions/NodeInfo/Dockerfile.armhf
- sample-functions/Phantomjs/Dockerfile
- sample-functions/ResizeImageMagick/Dockerfile
- sample-functions/ResizeImageMagick/Dockerfile.armhf
- sample-functions/SentimentAnalysis/Dockerfile
- sample-functions/SentimentAnalysis/Dockerfile.armhf
- sample-functions/figlet/Dockerfile
- sample-functions/figlet/Dockerfile.armhf
- watchdog/README.md
The following PR will enable all functions to use curl to get the watchdog since this can be cached by Docker.
The issue related to this PR is https://github.com/openfaas/faas/issues/841
The change implies only to the way watchdog is being get, so the verification was made by simply using docker build to build successfully each image for each architecture (where available).
> radoslav/sample functions - Use curl instead of ADD for getting the watchdog

- gateway/server.go
This commit adds basic authentication for `/system/async-report`
endpoint.
It also adds basic-auth secrets to `queue-worker` service which will be
used for gateway calls to `/system/async-report`.
This is required to fix https://github.com/openfaas/nats-queue-worker/issues/35 issue.
Test results have been added here. 
https://github.com/openfaas/nats-queue-worker/pull/36
> Add basic auth support for /system/async-report

- gateway/handlers/forwarding_proxy.go
- gateway/handlers/forwarding_proxy_test.go
This PR does the following:
*  Fix #847 by removing the http client host override
* X-Forwarded-For and X-Forwarded-Host are usually handled by the ingress controller, if those headers are not set then the gateway will create them
Tested using `stefanprodan/of-env:1.0.0`locally and on GKE with Istio ingress gateway.
Http_X_Forwarded_For was `127.0.0.1:44238` and after the patch it shows the real IP of the caller.
Http_X_Forwarded_Host is set by the gateway when no reverse proxy sets it first.
> Set upstream X-Forwarded Host and For headers if not present

- watchdog/README.md
- watchdog/build.sh
- watchdog/handler.go
- watchdog/main.go
- watchdog/requesthandler_test.go
Alter graceful shutdown sequence in classic watchdog
- the shutdown sequence meant that the kubelet was still passing
work to the watchdog after the HTTP socket was closed. This change
means that the kubelet has a chance to run its check before we
finally stop accepting new connections. It will require some
basic co-ordination between the kubelet's checking period and the
"write_timeout" value in the container.
Issue was shown by scaling to 20 replicas, starting a test with
hey and then scaling to 1 replica while tailing the logs from the
gateway. Before I saw some 502, now I see just 200s.
Tested with Kubernetes on GKE - before the change some Pods were
giving a connection refused error due to them being not detected
as unhealthy. …
> Watchdog: Alter graceful shutdown sequence

- gateway/metrics/exporter.go
- gateway/metrics/exporter_test.go
- gateway/metrics/prometheus_query.go
- gateway/plugin/external.go
- gateway/server.go
Enable basic auth for service query / scaling on provider
- this is a blocking issue for auth with Docker Swarm
fixes #879
Tested with Swarm along with @LucasRoesler verifying the results
gateway_service_count is now added back to the metrics and the auto-scaling is now working for Swarm because auth is available to pass to the provider.
In lieu of updating to a new release users can turn off `basic_auth` in `docker-compose.yml` for the faas-provider component. I also published `0.9.5-rc2` as a temporary tag for the gateway.
> Enable basic auth for service query / scaling on provider

- gateway/handlers/function_cache_test.go
- gateway/handlers/scaling.go
- gateway/plugin/external.go
- gateway/plugin/external_test.go
Within MakeScalingHandler() there is a call to GetReplicas() which was not returning an error when a non-200 http response was received from /system/function/.  The call would also return a populated struct, so the perception was that a function existed an had been scaled to zero.  This meant that the function would be added to the function cache and the code would continue into SetReplicas() where an attempt would be made to scale up a non-existent function.
This change amends GetReplicas() so that it will return an error if the gateway returns anything other than a 200 reponse code from the /system/function/ endpoint.  This causes MakeScalingHandler() to return earlier with an error indicating that the function could not be found.  The cache.Set call is also moved to after the error …
> Add checking for existent function in GetReplicas

- contrib/publish-armhf.sh
Avoided the `jq` dependency using `grep`. It still checks whether the `detail` pair has a value of `Not found` and based on that decides whether to build or not the ARMHF image.
> ARMHF publishing script - remove jq dependency

- community.md
- Add openfaas-operator as a provider with status Incubation
- Split the table into official providers and community providers
- Move the site links to the site column
- Strip some trailing whitespace 
using the markdown preview in vscode
> Feature add operator to providers list and split the providers table

- gateway/tests/integration/createfunction_test.go
- gateway/types/proxy_client.go
- Covers part of 919 by making the HTTP client used for proxying
stop following redirects. Tested with a stateless microservice,
but additional code changes may be requierd in the queue-worker,
the watchdogs and other areas.
Tested on Swarm with stateless microservice (Node.js) issuing
a redirect via Location header.
> Don't follow redirects from functions

- gateway/handlers/scaling.go
Adds logging around scale from zero events in scaling.go.  Previously scale from zero events were not logged in the same way that normal scaling events are.  This change adds log writes to show when a scale from zero was requested and when a function successfully moved to > 0 replicas.
Recent testing of related changes highlighted a gap in the logging around scale from zero events.  They were not being logged in the same was as normal scaling events making it difficult to track down such events.
Built the gateway image - rgee0/gateway:scaleLogging
Amended docker-compose.yml to enable scale from zero and changed the gateway image.
Ran `deploy_stack.sh`
Deployed `env` function
Ran `docker service scale env=0` and confrmed env had scaled to zero
```
ID                  NAME …
```
> Add logging to scale from zero requests

- gateway/handlers/alerthandler.go
- gateway/handlers/alerthandler_test.go
As reported on Slack and in issue #931 the gateway scaling code
was scaling to zero replicas as a result of the "proportional
scaling" added by @Templum's PR.
#931 
This commit added a failing test
which was fixed by adding boundary checking - now if the scaling
amount is "0" we keep the current amount of replicas.
> Update for scaling edge-case (fixes #931)

- .gitignore
Omit the staging directory created by the publish-armhf.sh script
> Update .gitignore to discard /contrib/staging/

- deploy_stack.ps1
This PR updates the Windows `deploy_stack.ps1` Powershell script to set the `basic-auth-user` and generate the `basic-auth-password` secrets if absent.
It also adds the following flags:
- `-help`, `-h`: print help text
- `-noAuth`, `-n`: disable basic auth
Deployed on Windows 10 with the following scenarios:
- No user or pass secret
- User secret exists, pass missing
- Pass secret exists, user missing
- Both user and pass secrets exist
> Create user/pass secrets and add help/noAuth flags to deploy_stack.ps1

- community.md
Signed-off-by: Patricio Diaz <padiazg@gmail.com>
Added an entry to the 2018 blog list
[Using GraphQL in OpenFaaS functions](https://padiazg.github.io/graphql-on-opesfaas/)
> Added blog entry Using GraphQL in OpenFaaS functions

- gateway/scaling/function_scaler.go
- gateway/scaling/scaling_config.go
- gateway/server.go
Enable backoff/retries on scaling up
This change is needed for Docker Swarm which may give an error
when several concurrent requests come in to scale a deployment.
Docker will throw an error about being out of sync which could
have prevented some requests from being served.
No issue is being raised, but this was found whilst working on
https://github.com/openfaas/nats-queue-worker/issues/32 with
high concurrency testing and watching the logs / completed
request count.
Tested on Docker Swarm before/after with the hey tool and figlet
scaled down to zero replicas.
> Enable backoff/retries on scaling up

- community.md
Signed-off-by: Swarvanu Sengupta <swarvanusg@gmail.com>
Add [faasflow](https://github.com/s8sg/faasflow) reference in the openfaas community
Faasflow is library that allows to build openfaas workflow with ease and deploy it as a function, This changes add faasflow reference at `community.md` file
> Add faasflow in the openfaas community reference

- gateway/handlers/alerthandler.go
- gateway/handlers/alerthandler_test.go
Signed-off-by: Gede Wahyu <tokekbesi@gmail.com>
- Fix replica calculation to enable scaled up from 1 when max replica or scale factor is small
When I have this config:
- current replica = 1
- max replica = 5
- scale factor = 30
it will never scaled up from 1. 
It will scaled up iff #MaxReplica * #ScaleFactor >= 200
I create new test case and already run test for `alerthandler_test.go`
Also tested on kubernetes using hey tool and figlet with max-replicas=5 and scale-factor=1
Result :
```
2018/12/01 18:02:13 [Scale] function=figlet 1 => 2.
2018/12/01 18:02:53 [Scale] function=figlet 2 => 3.
2018/12/01 18:03:33 [Scale] function=figlet 3 => 4.
2018/12/01 18:04:13 [Scale] function=figlet 4 => 5.
```
Result using default configuration, max-replicas=20 and scale-factor=20:
```
2018/12/01 …
```
> Scaled up from 1

- watchdog/handler.go
Use timer.AfterFunc to make sure goroutine could be gc.
Signed-off-by: Mike Chiu <mike.chiu@pentium.network>
Fix fwatchdog leak after stress testing or heavy loading.
Use time.AfterFunc to replace timer.NewTimer to avoid leak.
1. use build.sh to build fwatchdog image
2. run docker: ```docker run -it --entrypoint=sh --name=watchdog -p 8080:8080 {image}```
3. set env. variable: ```export fprocess="cat /etc/hostname"```
4. execute fwatchdog http server: ```fwatchdog```
5. outside the container, monitor stats of container: ```docker stats watchdog``` 
6. use ab to do stress testing: ```ab -n 1000 -c 100 https://localhost:8080```
> Fix fwatchdog timer memory leak issue

- .gitignore
- Vagrantfile
- api-docs/swagger.yml
- contrib/Vagrantfile
- gateway/requests/requests.go
- gateway/server.go
- gateway/types/handler_set.go
> Review/merge Secrets CRUD

- docker-compose.yml
I changed the version of image to current one,
which implements secret management endpoint (https://github.com/openfaas/faas-swarm/pull/42)
from 0.5.0 to 0.6.1 in docker-compose.yml (x86_64)
Also version of gateway was bumped from 0.9.11 to 0.9.14 (x86_64)
Signed-off-by: Bart Smykla <bsmykla@vmware.com>
I fired `./deploy_stack.sh` on my local machine
> Bumped version of faas-swarm to 0.6.1 and gateway to: 0.9.14

- gateway/Dockerfile.armhf
This change carries the changes made to `Dockerfile` when /system/info was introduces through to `Dockerfile.armhf`.  As well as the build-args which fix the identified issue the license check has also been added at the latest release 0.2.3, as a armhf build has been made available.  Further changes are to introduce the app user and moving the binary location from /root/ to /home/app/
Fixes #1040 
When the /system/info endpoint was expanded to include information about the gateway a number of build-args were added to the main Dockerfile.  These changes were not mirrored in Dockerfile.armhf, which resulted in nil attributes and an ugly error when running `faas version` against an armhf gateway.
Built on a Pi3:
```
$ ./build.sh
Building …
```
> Add build-args to Dockerfile.armhf

- docker-compose.arm64.yml
- docker-compose.armhf.yml
- docker-compose.yml
- gateway/server.go
- prometheus/alertmanager.yml
- Protect the `/system/alert` endpoint when basic auth is enabled
- Update the alert manager config to send the basic auth credentials
- Bump the gateway version
This issue was raised by @alexellis on slack
Tested manually in docker swarm and in k8s.
Create `spammer.sh`
```sh
#! /bin/bash
gateway=localhost:31112
fnc=cows
sleepSec=0
while true; do
echo "" | faas-cli invoke "$fnc" --gateway "$gateway"
sleep $sleepSec
done
```
In swarm (I have pushed a pre-built image to theaxer/gateway:0.10.0)
```sh
make build-gateway
docker tag openfaas/gateway:latest-dev openfaas/gateway:0.10.0
echo "testpass" | docker secret create basic-auth-password -
./deploy_stack.sh
export gateway=localhost:8080
curl -X POST http://$gateway/system/alert -d '{}'
faas-cli -g $gateway login -u admin --password testpass …
```
> Add basic auth to the system alert endpoint

- community.md
OpenFaaS is covered in the newly publish Serverless book Serverless Inside Out.
Committed by @nichochen
Follow-up of #1027
> Add a new book which covers OpenFaaS

- api-docs/swagger.yml
- Fixed annotations and labels type and added examples
- Added the readOnlyRootFilesystem bool
Fixes: #1059 
Swagger docs had inaccurate schema for labels and annotations
Tested with the Swagger Viewer VS Code plugin
> Updating the Swagger to be more accurate to address issue #1059

- docker-compose.yml
- Bumps the gateway version to 0.10.2 in the default docker-compose file
Continues the work started in #1049 to enable basic auth for the alert
endpoint, this will allow the deployment via compose to leverage the
basic auth
> Bump gateway version to 0.10.2 in compose

- gateway/handlers/forwarding_proxy.go
- gateway/plugin/external.go
- gateway/scaling/function_cache.go
- gateway/server.go
- gateway/types/proxy_client.go
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
Tune HTTP client for concurrency
- due to what appears to be a frequent issue with the Go HTTP
client some tweaks were needed to the HTTP client used for
reverse proxying to prevent CoreDNS from rejecting connections.
The following PRs / commits implement similar changes in
Prometheus and Minio.
https://github.com/prometheus/prometheus/pull/3592
https://github.com/minio/minio/pull/5860
These tweaks can be overridden with an environmental variable:
* `max_idle_conns` (default 1024)
* `max_idle_conns_per_host` (default 1024)
Under a 3-node (1-master) kubeadm cluster running on bare
metal with Ubuntu 18.04 I was able to send 100k requests
with 1000 being concurrent with no errors being returned
by hey.
```
helm upgrade openfaas …
```
> Tune HTTP client for concurrency

- docker-compose.yml
- prometheus/alert.rules.yml
- prometheus/k8s.alert.rules
- Removes the `alert` label in the scale-up alert
- Updates the annotaitons to use the `function_name` label instead of
the `instance` label that was removed.
- Per prometheus/prometheus#4836 and the related mailing list discussion
https://groups.google.com/d/msg/prometheus-users/7Ul6ngc7Ogs/j_YDszV5BwAJ
the alert value should not be included in the alert labels otherwise
each calculation of the alert is treated like a new alert and then the
use of `for 5s` will not behave as expected.
- Ports the resolution of openfaas/faas-netes#372
Resolves #1095
Tested manually on my Mac
1. deploy via the script
```sh
./deploy_stack.sh
```
2. deploy the go-echo function https://github.com/alexellis/echo-fn
3. create constant load using `hey`
```sh
hey -c 2 -q 10 -n 100000 …
```
> Upgrade prom and alert manager to 2.7.1 and 0.16.1

- watchdog/handler.go
- watchdog/requesthandler_test.go
Http_ContentLengh will be deprecated in the future.
Signed-off-by: Matias Pan <matias.pan26@gmail.com>
As discussed in #1127 this PR adds the environment variable `Http_Content_Length` but keeps `Http_ContentLength` to not introduce a breaking change. `Http_ContentLength` is considered deprecated and will be removed in the future.
Fixes #1127 
I built the watchdog, created a new function using it and tested that the contents of `Http_Content_Length` was being set correctly.
> Add Http_Content_Length to env variables

- gateway/handlers/forwarding_proxy.go
- gateway/handlers/forwarding_proxy_test.go
Requested by @LucasRoesler - removes headers detailed in HTTP
spec which are not supposed to be forwarded by proxies or
gateways.
HTTP compliance / standards.
Unit tested and tested by @LucasRoesler 
This is potentially a breaking change. I am extracting the work from #1130 so that we can review it properly in isolation.
> Remove hop headers

- .travis.yml
- watchdog/Dockerfile.packager
- watchdog/build.sh
Adds a packager Dockerfile to create an image that contains the fwatchdog binaries.
Fixes #969 
Successfully ran locally.
CI passed
> Bundle watchdog binaries into an image

- api-docs/swagger.yml
Fixed request body description for `POST /system/alert`.
Hope the new description is accurate, I couldn't give to much details, I'm just starting to look into openfaas 😉 
Resolves #1168
> Correct swagger Request description for /system/alert

- contrib/alertmanager-armhf/0.16.1/Makefile
- contrib/prometheus-armhf/2.2/Makefile
- contrib/prometheus-armhf/2.7.1/Makefile
- For each prometheus and alert manager contrib makefile, ensure that
the docker tag matches the version installed in the dockerfile.  This
will ensure that no one pushes mismatched versions
Resolves #1172 
Relates to https://github.com/openfaas/faas-netes/pull/425
Ran the makefiles locally to ensure that the resulting tag was passed correctly
> Ensure contib prom docker tags match the installed version

- community.md
Adding the Dockercon OSS Summit: Serverless to the community file.
There isn't yet a separate page for the Serverless Summit, so I've linked to the main OSS Summit page for now. Hopefully this gets added soon and I will PR an update for the link
N/A
N/A
N/A
> Add Dockercon Serverless Summit to community

- gateway/handlers/external_auth.go
- gateway/handlers/external_auth_test.go
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
This commit adds an external auth handler which can be used to
wrap existing handlers, so that they delegate their requests
to an upstream URL before allowing a request to pass through
to an upstream API.
Gateway config also gains two new options:
* auth_proxy_url
* auth_proxy_pass_body
#1209 #1210 
The new handler has been tested with unit tests for positive / negative cases
> Add external auth handler and gateway config options

- deploy_stack.sh
- docker-compose.yml
As part of #1209, this change deploys, but does not enable the
new basic-auth plugin service.
#1209 
Deploying to Swarm with the edited ./deploy_stack.sh - and seeing the service available.
> Deploy basic auth plugin

- docker-compose.yml
- gateway/handlers/basic_auth_injector.go
- gateway/handlers/basic_auth_injector_test.go
- gateway/handlers/forwarding_proxy.go
- gateway/handlers/serviceauthinjector.go
- gateway/plugin/external.go
- gateway/plugin/external_test.go
- gateway/server.go
- gateway/types/handler_set.go
Switch gateway to external auth
This commit moves the OpenFaaS gateway from using in-process
basic-auth for everything to use an external auth URL instead.
When auth is not enable, this functionality is not added to the
handlers and behaves as before. When enabled, the configured
plugin with authenticate requests.
#1209 
Tested e2e on Docker Swarm with positive and negative tests.
> Switch gateway to external auth 

- .github/FUNDING.yml
Adds github/alexellis. Detail was removed on 10th June with a comment that it will be enabled once GitHub provide access to the beta.  This access was provided on 12th June hence re-enabling.
Non-functional change
> Update FUNDING.yml to enable github/alexellis

- watchdog/Gopkg.lock
- watchdog/README.md
- watchdog/handler.go
- watchdog/metrics/metrics.go
- watchdog/readconfig.go
- watchdog/vendor/github.com/openfaas/faas-middleware/LICENSE
- watchdog/vendor/github.com/openfaas/faas-middleware/concurrency-limiter/concurrency_limiter.go
This enables limiting concurrency. It is a naive approach which
will reject requests as soon as they exceed the maximum number
of in-flight requests.
Porting over changes: https://github.com/openfaas-incubator/of-watchdog/pull/54
* There are significant tests inside of the concurrency-limiter itself
* It was tested using go test, but due to the test `TestHealthHandler_StatusOK_LockFilePresent` being flakey, it was difficult to test with go test -count=1000
> Add Concurrency Limiter

- deploy_stack.armhf.sh
Considering that there's now a single `deploy-stack.sh` script, I believe there's no reason to keep a separate one for armhf. 
I understand the reason is to not break any old references, but some time has passed since that change and at the end it might be even rather confusing to keep it.
> Remove deploy-stack.armhf.sh script

- gateway/assets/script/bootstrap.js
- gateway/assets/templates/newfunction.html
The customize button was redundant to the custom tab
This could lead to confusion with the user experience,
so the additional button has been removed.
Deployed new version of the gateway locally, and confirmed button is no longer present, and function deployments still function as expected.
This is in response to https://github.com/openfaas/faas/pull/1189#issuecomment-497682330
> Remove extra customize button

- .travis.yml
- Makefile
- auth/basic-auth/Makefile
- auth/basic-auth/build.sh
- auth/basic-auth/push.sh
- build.sh
- ci/tagAndPush.sh
- contrib/publish-arm.sh
Automatic builds for auth-module on x86_64 (via Travis) and on-demand on-device for arm via publish.sh
The basic-auth module is not built or pushed upon 'tag' / 'release' of the faas repo, but it should be: https://github.com/openfaas/faas/tree/master/auth.  We also don't create on-device images for this, but should do for both armhf and arm64: https://github.com/openfaas/faas/blob/master/contrib/publish-arm.sh
This change addresses these challenges and also introduces a tagAndPush script to alleviate some of the recently introduced repetition in .travis.yml.
The new build and push files for the auth plugin follow the pattern established for the gateway component.  The top level Makefile has calls to the new scripts added in the …
> Refactor CI and enable auto-builds for auth

- watchdog/handler.go
Just add logs to watchdog for easy debugging
No tests are required
> chore: add log for easy debug

- CONTRIBUTING.md
- Expand the Contribution guide so to describe using `goleak` in unit
tests.  This package provides a simple method for detecting goroutine
leaks in tests. This will help ensure that we write safe code.
Resolves #1248 
No tests are required beyond reading the Contribution.md file
> Document goleak usage

- gateway/Dockerfile
- gateway/Makefile
- gateway/build.sh
Collapse Dockerfile.armhf into Dockerfile
Relates to #1257 
CGO_ENABLED and GOARM etc are now passed as ARGs via build.sh.
This change which has been tested on armhf and x86_64 removes
the need for a separate Dockerfile for armhf.
The store values showed as expected, after some initial issues
I found, where the `ARG` has to be redeclared for multi-stage builds.
Refactoring
This can be merged, and I'll remove Dockerfile.armhf after testing the publish-arm script.
> Collapse Dockerfile.armhf into Dockerfile

- CONTRIBUTING.md
Update Governance and Team structure
Updated verbiage from "contributors" to "team" for members and
core. Added project sponsor OpenFaaS Ltd, trademark and additional
perks / benefits for members.
Setting norms, ground-rules, perks and vision for voluntary teams.
> Update Governance and Team structure

- api-docs/swagger.yml
- Corrects indentation for the /system/logs endpoint (summary,...)
- Fixes schema validation for LogEntry
Fixes errors in the api docs as raised in #1287 
Loaded the API Docs into Swagger Editor and they validate without errors.
> Fix api docs for logging endpoint

- gateway/Gopkg.lock
- gateway/Gopkg.toml
- gateway/server.go
- gateway/types/handler_set.go
- gateway/vendor/github.com/openfaas/faas-provider/types/config.go
Add namespaces endpoint to gateway
https://github.com/openfaas/faas-netes/issues/511
This is being added because multiple namespaces can now be used
on Kubernetes. By listing namespaces, a client such as the UI
or CLI can then enumerate the namespaces to find functions
which may span across more than one namespace.
> Add namespaces endpoint

- gateway/requests/requests.go
Signed-off-by: Jonatas Baldin <jonatas.baldin@gmail.com>
Enables Namespace in Secret. Depends on [faas-provider #28](https://github.com/openfaas/faas-provider/pull/28).
> Add Namespace to Secret type

- CONTRIBUTING.md
False expectations from commercial users has been a source of
contention in Open Source since the beginning. This is designed
to help bring some empathy and understanding, and set more
realistic expectations for commerical users.
> Set expectations for those seeking free support

- contrib/publish-arm.sh
The response for an image tag that has not been found is inside a JSON elemnt of "message" not the stated "details", it has also been lower-cased.
Signed-off-by: Alistair Hey <alistair.hey@gmail.com>
The publish-rm.sh script was calling out to dockerhub but not correctly working out if the tag exists - Think the api now returns lowercase rather than uppercase.
#1360
> ISSUE-1360: change to looking for lower-case response from dockerhub 

- ADOPTERS.md
Updated ADOPTERS.md to Include Ratehub
Signed-off-by: Chris Richard <chris.richard@ratehub.ca>
> Include Ratehub in the list of OpenFaaS adopters

- docker-compose.arm64.yml
- docker-compose.armhf.yml
- docker-compose.yml
- Bump faas-swarm version to latest, 0.8.2
- Bump arm64 and armhf services to their latest versions
- The docker-compose files were invalid when deployed directly because
the auth url was not configured.  Set the default for basic auth to
false to make this a valid configuration
This is require to keep the swarm installation up to date with the latest release.
I have deployed to my local docker swarm (on Mac) using the standard `./deploy_stack.sh`, with basic auth enabled.  I was able to access the web UI, deploy, and invoke a function. As usual.
> Update swam provider version in compose to 0.8.2

- community.md
The vCenter Event Broker Appliance (VMware Fling) uses OpenFaaS to
trigger functions based on vSphere events.
Signed-off-by: Michael Gasch <mgasch@vmware.com>
> Add vCenter Event Broker Appliance to projects

- gateway/Gopkg.lock
- gateway/Gopkg.toml
- gateway/README.md
- gateway/server.go
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
- gateway/vendor/github.com/openfaas/nats-queue-worker/handler/handler.go
This PR allows for customizing the NATS Streaming cluster name via `faas_nats_cluster_name`. It is a companion PR to https://github.com/openfaas/nats-queue-worker/pull/71.
Same as https://github.com/openfaas/nats-queue-worker/pull/71.
> Allow for customizing the name of the target NATS Streaming cluster.

- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
This is a precursor to adding a dropdown for namespaces
selection (#1379)
#1379
Deployed a self-built gateway (built using make, and push.sh) to my OF installation (by updating the deployment and checking it deployed my image)
Functions load, new namespace indicator is on the function detail page (see screenshot)
> Add Namespace indicator on Function page part of #1379

- gateway/Gopkg.lock
- gateway/Gopkg.toml
- gateway/README.md
- gateway/server.go
- gateway/types/readconfig.go
- gateway/types/readconfig_test.go
- gateway/vendor/github.com/openfaas/nats-queue-worker/handler/handler.go
This PR adds support for customising the NATS Streaming channel used for asynchronous invocations, as per openfaas/faas#1399, in a backwards-compatible way.
https://github.com/openfaas/faas/issues/1399
By running the included unit tests, which is enough in this case IMHO. There's also `bmcstdio/openfaas-gateway:pr-1400`, just in case.
> Support customising the NATS Streaming channel.

- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
- gateway/assets/templates/newfunction.html
We now hide the new namespace dropdown selector when
there is only 1 namespace, or when we are on swarm
This is also hidden in the function create page and
the function detail page
closes #1391 
Deployed to Swarm, namespace selectors all hidden, can create invoke and delete functions
Deployed to k8s with 1 namespace, its all hidden and create/invoke/delete work
Deployed to k8s with >1 ns, its visible, selectable and we can create, invoke and delete functions in each ns
> Hide the namespace selector when on swarm or <2 K8s ns

- gateway/assets/index.html
- gateway/assets/script/bootstrap.js
- gateway/assets/style/bootstrap.css
- gateway/assets/templates/newfunction.html
The initial namespace select implementation had some challenges, especially around non-default installs (no openfaas-fn namespace)
This has removed lots of those issues and added some more user friendly bits too (defaulting to first returned namespace from backend, passing that namespace to the function-create as default)
closes #1408 
closes #1408 
kubernetes:
Install with 4 active namespaces, switching works, adding a fn works (for each namespace)
Can add the same fn to each namespace
Can call each fn, see it calls correct one in logs
Can delete functions
Swarm:
No NS selector, can create, call and delete fns.
> Change how and when we fetch and parse namespace info

- gateway/server.go
Always apply the `FunctionPrefixTrimmingURLPathTransformer` when enqueueing async function requests. This ensures that the context information sent to the function is correct.
Resolves openfaas/nats-queue-worker#85
Manually tested locally 
```sh
$ kind version
kind v0.6.1 go1.13.4 darwin/amd64
$ kind create cluster
$ helm repo add openfaas https://openfaas.github.io/faas-netes/ && helm repo update
$ kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
$ helm upgrade openfaas --install openfaas/openfaas \
--namespace openfaas  \
--set functionNamespace=openfaas-fn \
--set generateBasicAuth=true \
--set gateway.directFunctions=false \
--set queueWorker.gatewayInvoke=true \
--set gateway.image=theaxer/gateway:fix-85
$ kubectl port-forward -n openfaas …
```
> Always apply the function prefix trim for async functions

- watchdog/README.md
- watchdog/handler.go
- watchdog/requesthandler_test.go
Add transfer-encoding to watchdog env-vars if present
The Content-Type header must be ignored when the Transfer
Encoding is set to "chunked" because the length is unknown
Go sets this to -1 and we pass that onto the user:
https://golang.org/src/net/http/transfer.go
The value of Content_Length is currently set to -1 in this
scenario, however it caused some confusion for at least one
user in issue: #1422.
The Http_Transfer_Encoding value was tested by running the
watchdog on Linux with "env" as the fprocess and an extra
header to "curl"
> Add transfer-encoding to watchdog env-vars if present

- deploy_stack.ps1
Adds the missing `$env:BASIC_AUTH` and `$env:AUTH_URL` envvars to the windows `deploy_stack.ps1` script.
Fixes #1308 
Deployed both with and without auth on Windows 10.
With auth - verified by logging in via incognito browser and confirming prompt for basic auth creds.
```
PS D:\workspace\github\openfaas\faas> powershell -ExecutionPolicy Bypass -File .\deploy_stack.ps1      
Attempting to create credentials for gateway..
[Credentials]
username: admin
password: 2a92d6f29b7a70495b9d25519c75b8d2612a9a61784fa56073931867de39f158
Write-Output "2a92d6f29b7a70495b9d25519c75b8d2612a9a61784fa56073931867de39f158" | faas-cli login --username=admin --password-stdin
Enabling basic authentication for gateway..
Deploying OpenFaaS core services
Creating config func_alertmanager_config
Creating config …
```
> Fix envvar handling in deploy_stack.ps1

- community.md
Spoke on RISC-V Summit 2019 about cloud technologies on RISC-V architecture and did a demo of OpenFaaS.
Added to community.md the video of the talk.
> Add talk on RISC-V Summit 2019

- community.md
Add video links to Kubecon talks in the community file
Some of the talks were already present with a link to the event, so I've just added an additional link to the existing row for the video so as not to lose the event information.
If you'd rather have duplicated records, one for the event, and one for the video, I'm happy to refactor this change. Perhaps the video link could go into the "writeups" section with some of the other videos.
Spoke with Alex via Slack
Verified the links were functional and previewed the markdown rendering with VSCode
> Add 3 KubeCon video links to community file

- sample-functions/hey/Dockerfile
- sample-functions/hey/readme.md
Add a sample `hey` function.
It is important to load test. Why not have a function to help do it?
1.  I built the function on my local machine, and confirmed that subsequent builds were cached.
2.  I pushed the function to my personal Docker Hub.
3.  I deployed Nodeinfo and this temporary build of the hey function to my personnel OpenFaaS.
4.  I confirmed `hey` provides results like it does on the CLI.
N/A
1. My cluster is running in Digital Ocean. I started using DO from a referral link from one of Alex's posts. I setup my cluster `ark` in about 15 minutes. I love `ark`.
2. After running the steps above (1-4), I deleted both functions from my cluster.
3. Screenshot of deployed function
4. Rresults 
```
Summary:
Total:	1.5234 secs
Slowest:	1.5058 secs
Fastest:	0.0027 secs
Average:	0.1133 …
```
> Hey sample function

- community.md
Adding two blog posts in medium by Hans van den Akker
which mention and use OpenFaaS
Adding blog posts to community.md
N/A community file change
> Add two blog posts by Hans van den Akker

- gateway/plugin/external.go
Remove service namespace from scale request
This field doesn't appear to be used and is supplied via the
querystring which faas-netes (the only ns-enabled provider
already consumes)
Related to PR:
https://github.com/openfaas/faas-netes/pull/671
Go test and local make with Dockerfile.
> Remove service namespace from scale request

- api-docs/swagger.yml
Fixes #1578
Change `FunctionDefintion` to `FunctionDefinition`
Signed-off-by: yankeexe <yankee.exe@gmail.com>
Typo fixed for swagger API preview.
> Update typo under definitions

- gateway/handlers/notifiers.go
- gateway/main.go
- gateway/metrics/add_metrics.go
- gateway/metrics/add_metrics_test.go
- gateway/metrics/exporter.go
- gateway/metrics/exporter_test.go
This commit adds namespace in function names while logging metrics to
prometheus, irrespective of the function is invoked with namespace suffix
or not.
This is also required to add multiple namespace support to faas-idler
https://github.com/openfaas-incubator/faas-idler/issues/37 which is part
of https://github.com/openfaas/faas-netes/issues/511
> Add namespace in function name for metrics

- gateway/metrics/exporter.go
Fix a bug that caused the services list to keep growing
This patch changes the code which looks up service and appends
them to the Exporter's list. It previously would create an
endless list and cause a memory leak.
> Fix a bug that caused the services list to keep growing

- gateway/main.go
- gateway/plugin/external.go
Update scaling polling interval
Polls every 100 ms instead of every 50ms for use with a new
faas-netes PR:
https://github.com/openfaas/faas-netes/pull/726
The call is much faster now, so this request should me made
at a lower frequency.
Also adds error handling for URL building in the external
service query code.
Tested in the faas-netes PR at 150ms which seemed too slow, so this PR just adds
50ms to the interval.
> Update scaling polling interval

- .github/workflows/publish.yml
This fixes the Github Actions CI to publish the correct auth container
tag. Previously it was using latest-dev not the git tag
> Use correct tag on publishing basic-auth container

- gateway/main.go
Restore the X-Call-Id for synchronous calls
This appears to have been removed inadvertently whilst
adding scale from zero logic into the gateway.
Going forward, synchronous and asynchronous calls will have a
header populated.
Fixes: #1624 
The "env" function can be used to print headers and show the behaviour before, and after.
Verify previous behaviour with:
```
arkade install openfaas \
--set gateway.image=alexellis2/gateway:0.1.0
faas-cli deploy --name env --fprocess env \
--image functions/alpine:latest-multiarch
curl localhost:8080/function/env
Http_User_Agent=curl/7.72.0
Http_Accept=*/*
Http_X_Forwarded_For=127.0.0.1:42484
Http_X_Forwarded_Host=localhost:8080
Http_Accept_Encoding=gzip
Http_Method=GET …
```
> Restore the X-Call-Id for synchronous calls

- gateway/handlers/notifier_wrapper_test.go
- Add unit test that verifies the behavior of the logging middleware in
various response cases
An issue with logging came up in Slack and this shows that the issue is not in the notification or logging middlewares
It is a unit test
> Add explicit test for the logging notifier middleware

- community.md
👋 
There was an extra newline character after the first entry in the `Interviews and podcasts` sections breaking the markdown preview. Corrected it.
Signed-off-by: Andreas Mosti <andreas.mosti@gmail.com>
> Removed newline and corrected markdown-table for Interviews and podcasts in community.md

- gateway/main.go
- gateway/metrics/exporter.go
- gateway/metrics/metrics.go
- gateway/requests/requests.go
- gateway/types/handler_set.go
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alex@openfaas.com>
Remove OpenFaaS Pro metrics from OpenFaaS CE
* Removes service min and target metrics from the CE gateway
OpenFaaS Pro metrics are no longer required in OpenFaaS CE since there is an OpenFaaS Pro gateway available.
Building and running the local tests.
> Remove OpenFaaS Pro metrics from OpenFaaS CE

- gateway/go.mod
- gateway/handlers/notifier_handler.go
- gateway/vendor/github.com/openfaas/faas-provider/httputil/write_interceptor.go
- gateway/vendor/github.com/openfaas/faas-provider/httputil/writers.go
- gateway/vendor/modules.txt
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alex@openfaas.com>
Use write interceptor from faas-provider
We now have two write interceptors, with one moved into faas-provider. This commit makes the gateway use the new external package and deletes its own.
Used by @welteki e2e within a cluster under load from hey.
This change is also going into the OpenFaaS Pro gateway
Consolidation / maintenance
> Use write interceptor from faas-provider

- gateway/metrics/add_metrics.go
- gateway/metrics/add_metrics_test.go
Return the original upstream response body when the the list request returns an error. In general, the provider is returning useful and actionable error messages for the user, the previous code hid this in the logs and this is easy for user to overlook.
Additionally, remove an early return from error case after fetching metrics. This looked like a bug and could result in empty api responses if there was a prometheus error.
This is related to  openfaas/faas-netes#1031 and openfaas/faas-netes#1022
Additional test has been added
> fix: return provider response during fnc listing errors

- gateway/handlers/infohandler.go
ioutil.ReadAll will delete in future
Signed-off-by: 流雨声 <212724256@qq.com>
> fix: use io.ReadAll  replace ioutil.ReadAll

- api-docs/spec.openapi.yml
The ScaleFunction request supports specifying the function namespace. This is now included in the API spec.
This issue was discussed during the last Community call
NA
> docs: add missing namespace field to the scale request

- gateway/Dockerfile
- gateway/Makefile
- gateway/go.mod
- gateway/go.sum
- gateway/handlers/forwarding_proxy.go
- gateway/vendor/github.com/openfaas/faas-provider/httputil/write_interceptor.go
- gateway/vendor/github.com/openfaas/faas-provider/types/system_events.go
- gateway/vendor/modules.txt
Support streaming responses from functions
When responses are written back piece-by-piece through Server Sent Events, the gateway was buffering all of the text then sending it at once, or missing some data. This change implements custom handling for the content-type of `text/event-stream`
```python
from flask import stream_with_context, request,Response
import requests
from langchain_community.chat_models import ChatOpenAI
from os import environ
environ["OPENAI_API_KEY"] = "Bearer foo"
chat_model = ChatOpenAI(
model="gpt-3.5-turbo",
openai_api_base="https://openai.inlets.dev/v1",
)
def handle(app, req):
def stream():
for chunk in chat_model.stream("You are a helpful AI assistant, try your best to help, respond with truthful answers, but if you don't know the correct answer, say so. Answer …
```
> Support streaming responses from functions
